# EDA Notebook

# Table of Contents
1. [Player Info Data](#first-point)
    - [Importing and Merging Data](#first-first-subpoint)
    - [Deal with `height` column](#first-second-subpoint)
    - [Deal with `weight` column](#first-third-subpoint)
    - [Deal with `college` column](#first-fourth-subpoint)
    - [Deal with `born` column](#first-fifth-subpoint)
    - [Deal with `birth_state` and `birth_city` columns](#first-sixth-subpoint)
    - [Deal with `year_start` column](#first-seventh-subpoint)
    - [Deal with `year_end` column](#first-eighth-subpoint)
    - [Deal with `position` column](#first-nineth-subpoint)
    - [Deal with `birth_date` column](#first-tenth-subpoint) 
2. [Player Statistics Data](#second-point)
    - [Importing Data](#second-first-subpoint)
    - [General Cleaning](#second-second-subpoint)
    - [Deal with `Year` column](#second-third-subpoint)
    - [Deal with `Player` column](#second-fourth-subpoint)
    - [Merge](#second-fifth-subpoint)
    - [The Problem with Stats Before 1974](#second-sixth-subpoint)
    - [Deal with `Pos` and `positions` columns](#second-seventh-subpoint)
    - [Deal with `Age` column](#second-eighth-subpoint)
    - [Deal with `Tm` column](#second-nineth-subpoint)
    - [Deal with `G` column](#second-tenth-subpoint)
    - [Deal with `GS` column](#second-eleventh-subpoint)
    - [Deal with `MP` column](#second-twelfth-subpoint)
    - [Deal with `PER` column](#second-thirteenth-subpoint)
    - [Deal with `TS%` column](#second-fourteenth-subpoint)
    - [Deal with `3PAr` column](#second-fifteenth-subpoint)
    - [Deal with `FTr` column](#second-sixteenth-subpoint)
    - [Deal with `TRB` column](#second-seventeenth-subpoint)
    - [Deal with `ORB` and  `ORB%` columns](#second-eighteenth-subpoint)
    - [Deal with `DRB` and  `DRB%` columns](#second-nineteenth-subpoint)
    - [Deal with `TRB%` column](#second-twentieth-subpoint)
    - [Deal with `AST%`, `STL%`, `BLK%`, `TOV%`, and `USG%` columns](#second-twenty-first-subpoint)
    - [Deal with `OWS` column](#second-twenty-second-subpoint)
    - [Deal with `DWS` column](#one-more)
    - [Deal with `WS` and `WS/48` column](#second-twenty-third-subpoint)
    - [Deal with `FG%` column](#second-twenty-sixth-subpoint)
    - [Deal with `3P`, `3PA`, and `3P%` columns](#second-twenty-seventh-subpoint)
    - [Deal with `2P%` column](#second-twenty-eighth-subpoint)
    - [Deal with `eFG%` column](#second-twenty-ninth-subpoint)
    - [Deal with `FT%` column](#second-thirtieth-subpoint)
    - [Deal with `TOV` column](#second-thirty-first-subpoint)
    - [Deal with `hall_of_fame` columns](#second-thirty-second-subpoint)
    - [Deal with `year_start` and `year_end` columns](#second-thirty-third-subpoint)
    - [Dtype Changes](#second-thirty-fourth-subpoint)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import os
import math
import datetime as dt

# Cleaning Data<a name="first-step"></a>

## Player Info Data<a name="first-point"></a>

### Importing and Merging Data<a name="first-first-subpoint"></a>

Import and check first few rows of "Player" csv. This table includes information about the players such as where they were born, their college, their height, etc. This does not include their stats in their career. We have two tables like this that contain some of the same information but some different columns. So the following is the first one. Once we import this one, we will import the other one, merge them, and then clean the info.

In [2]:
playerInfoDf1 = pd.read_csv('/Users/aidenbailey/Documents/BrainStation_Class/Capstone/Data/Players.csv', index_col=0)
playerInfoDf1.head()

Player  height  weight                          collage    born  \
0  Curly Armstrong   180.0    77.0               Indiana University  1918.0   
1     Cliff Barker   188.0    83.0           University of Kentucky  1921.0   
2    Leo Barnhorst   193.0    86.0         University of Notre Dame  1924.0   
3       Ed Bartels   196.0    88.0  North Carolina State University  1925.0   
4      Ralph Beard   178.0    79.0           University of Kentucky  1927.0   

    birth_city birth_state  
0          NaN         NaN  
1     Yorktown     Indiana  
2          NaN         NaN  
3          NaN         NaN  
4  Hardinsburg    Kentucky

Rename the "collage" column to 'college' (correcting typo) and renaming 'Player' to 'name' to match second dataframe.

In [3]:
playerInfoDf1.rename(columns={'collage':'college', 'Player':'name'}, inplace=True)

In [4]:
# Checking info and nulls
playerInfoDf1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3922 entries, 0 to 3921
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   name         3921 non-null   object 
 1   height       3921 non-null   float64
 2   weight       3921 non-null   float64
 3   college      3573 non-null   object 
 4   born         3921 non-null   float64
 5   birth_city   3452 non-null   object 
 6   birth_state  3439 non-null   object 
dtypes: float64(3), object(4)
memory usage: 245.1+ KB


Let's check for duplicate names.

There are astrisks next to some names indicating if a player was inducted into the Hall of Fame. We will remove that astrisk but create a new column indicating Hall of Fame status as well.

In [5]:
# Check if displaying correct rows
hall_of_famers = playerInfoDf1.loc[playerInfoDf1['name'].str.endswith('*')==True, :]
hall_of_famers

name  height  weight                            college  \
26            Al Cervi*   180.0    77.0                                NaN   
39          Bob Davies*   185.0    79.0              Seton Hall University   
54           Joe Fulks*   196.0    86.0            Murray State University   
57      Harry Gallatin*   198.0    95.0            Truman State University   
74         Alex Hannum*   201.0    95.0  University of Southern California   
...                 ...     ...     ...                                ...   
2219   Alonzo Mourning*   208.0   108.0              Georgetown University   
2222  Shaquille O'Neal*   216.0   147.0         Louisiana State University   
2432   Arvydas Sabonis*   221.0   126.0                                NaN   
2479     Allen Iverson*   183.0    74.0              Georgetown University   
2878          Yao Ming*   229.0   140.0                                NaN   

        born   birth_city   birth_state  
26    1917.0      Buffalo      New York  
39    1920.0   Harrisburg  Pennsylvania  
54    1921.0   Birmingham      Kentucky  
57    1927.0       Roxana      Illinois  
74    1923.0  Los Angeles    California  
...      ...          ...           ...  
2219  1970.0   Chesapeake      Virginia  
2222  1972.0       Newark    New Jersey  
2432  1964.0       Kaunas     Lithuania  
2479  1975.0      Hampton      Virginia  
2878  1980.0     Shanghai         China  

[127 rows x 7 columns]

In [6]:
hall_of_fame_names = list(hall_of_famers['name'].values)
playerInfoDf1['hall_of_fame'] = None

for name in playerInfoDf1['name']:
    if name in hall_of_fame_names: # If they are in the hall of fame...
        playerInfoDf1.loc[playerInfoDf1['name']==name, 'hall_of_fame']  = 1 # Indicate they are here
        playerInfoDf1.loc[playerInfoDf1['name']==name, 'name'] = name[:-1] # Remove the astrisk here
        
playerInfoDf1['hall_of_fame'].fillna(0, inplace=True)

In [7]:
# Check if there are astrisks remaining
playerInfoDf1.loc[playerInfoDf1['name'].str.endswith('*')==True, :]

Empty DataFrame
Columns: [name, height, weight, college, born, birth_city, birth_state, hall_of_fame]
Index: []

In [8]:
playerInfoDf1.loc[playerInfoDf1['hall_of_fame']==1, ['name', 'hall_of_fame']]

name  hall_of_fame
26            Al Cervi             1
39          Bob Davies             1
54           Joe Fulks             1
57      Harry Gallatin             1
74         Alex Hannum             1
...                ...           ...
2219   Alonzo Mourning             1
2222  Shaquille O'Neal             1
2432   Arvydas Sabonis             1
2479     Allen Iverson             1
2878          Yao Ming             1

[127 rows x 2 columns]

In [9]:
# Convert weight from kilograms to pounds
playerInfoDf1['weight'] = round(playerInfoDf1['weight']*2.205, 1)

In [10]:
# Sanity check
playerInfoDf1['weight'].head()

0    169.8
1    183.0
2    189.6
3    194.0
4    174.2
Name: weight, dtype: float64

In [11]:
# Convert height from centimeters to inches
playerInfoDf1['height'] = round(playerInfoDf1['height']*0.393701, 1)

In [12]:
# Sanity check
playerInfoDf1['height'].head()

0    70.9
1    74.0
2    76.0
3    77.2
4    70.1
Name: height, dtype: float64

In [13]:
# Remove decimal from 'born' column
playerInfoDf1['born'] = [int(num) if math.isnan(num)==False else 'Unknown' for num in playerInfoDf1['born']]
playerInfoDf1['born'].head()

0    1918
1    1921
2    1924
3    1925
4    1927
Name: born, dtype: object

We will now import the second player data table.

In [14]:
playerInfoDf2 = pd.read_csv('/Users/aidenbailey/Documents/BrainStation_Class/Capstone/Data/player_data.csv')
playerInfoDf2.head()

name  year_start  year_end position height  weight  \
0       Alaa Abdelnaby        1991      1995      F-C   6-10   240.0   
1      Zaid Abdul-Aziz        1969      1978      C-F    6-9   235.0   
2  Kareem Abdul-Jabbar        1970      1989        C    7-2   225.0   
3   Mahmoud Abdul-Rauf        1991      2001        G    6-1   162.0   
4    Tariq Abdul-Wahad        1998      2003        F    6-6   223.0   

         birth_date                                college  
0     June 24, 1968                        Duke University  
1     April 7, 1946                  Iowa State University  
2    April 16, 1947  University of California, Los Angeles  
3     March 9, 1969             Louisiana State University  
4  November 3, 1974              San Jose State University

In [15]:
playerInfoDf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4550 entries, 0 to 4549
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        4550 non-null   object 
 1   year_start  4550 non-null   int64  
 2   year_end    4550 non-null   int64  
 3   position    4549 non-null   object 
 4   height      4549 non-null   object 
 5   weight      4544 non-null   float64
 6   birth_date  4519 non-null   object 
 7   college     4248 non-null   object 
dtypes: float64(1), int64(2), object(5)
memory usage: 284.5+ KB


In [16]:
playerInfoDf2.tail()

name  year_start  year_end position height  weight  \
4545   Ante Zizic        2018      2018      F-C   6-11   250.0   
4546     Jim Zoet        1983      1983        C    7-1   240.0   
4547    Bill Zopf        1971      1971        G    6-1   170.0   
4548  Ivica Zubac        2017      2018        C    7-1   265.0   
4549   Matt Zunic        1949      1949      G-F    6-3   195.0   

             birth_date                       college  
4545    January 4, 1997                           NaN  
4546  December 20, 1953         Kent State University  
4547       June 7, 1948           Duquesne University  
4548     March 18, 1997                           NaN  
4549  December 19, 1919  George Washington University

Let's check for duplicate names:

In [17]:
playerInfoDf2.loc[playerInfoDf2['name'].duplicated()==True, :].sort_values('name')

name  year_start  year_end position height  weight  \
424       Bill Bradley        1968      1977      F-G    6-5   205.0   
1069         Bob Duffy        1963      1965        G    6-3   185.0   
2063       Bobby Jones        2007      2008        F    6-7   215.0   
4431      Bobby Wilson        1975      1978        G    6-3   175.0   
1715  Cedric Henderson        1998      2002        F    6-7   215.0   
2066     Charles Jones        1985      1989        F    6-8   215.0   
2067     Charles Jones        1999      2000        G    6-3   180.0   
3734     Charles Smith        1998      2006        G    6-4   194.0   
3733     Charles Smith        1990      1996        G    6-1   160.0   
2000     Chris Johnson        2013      2016      F-G    6-6   206.0   
3736       Chris Smith        2014      2014        G    6-2   200.0   
4496      Chris Wright        2013      2013        G    6-1   210.0   
80        Dan Anderson        1975      1976        G    6-2   185.0   
2359         David Lee        2006      2017        F    6-9   245.0   
4138      David Vaughn        1996      1999        F    6-9   240.0   
488          Dee Brown        2007      2009        G    6-0   185.0   
3743         Don Smith        1975      1975        G    6-0   160.0   
2011     Eddie Johnson        1982      1999      F-G    6-7   215.0   
2393     Freddie Lewis        1967      1977        G    6-0   175.0   
3146       Gary Payton        2017      2018        G    6-3   190.0   
2016    George Johnson        1973      1986      C-F   6-11   205.0   
2017    George Johnson        1979      1986      F-C    6-7   210.0   
1718  Gerald Henderson        2010      2017        G    6-5   215.0   
3369         Glen Rice        2014      2015        G    6-6   206.0   
3430    Glenn Robinson        2015      2017      G-F    6-6   222.0   
3750        Greg Smith        2012      2016        C   6-10   250.0   
4088       Jack Turner        1962      1962      G-F    6-5   200.0   
3137        Jim Paxson        1980      1990      G-F    6-6   200.0   
2027       Ken Johnson        2003      2003      F-C   6-11   240.0   
1055        Larry Drew        2015      2015        G    6-2   180.0   
2030     Larry Johnson        1992      2001        F    6-6   250.0   
2910       Larry Nance        2016      2018        F    6-9   230.0   
1923      Luke Jackson        2005      2008        F    6-7   215.0   
4393   Marcus Williams        2008      2009        F    6-7   205.0   
925         Mark Davis        1996      2000      G-F    6-7   210.0   
2094        Mark Jones        2005      2005        G    6-6   215.0   
1563       Matt Guokas        1967      1976      G-F    6-5   175.0   
3767     Michael Smith        1995      2001        F    6-8   230.0   
929         Mike Davis        1983      1983        F   6-10   230.0   
1080     Mike Dunleavy        2003      2017      F-G    6-9   230.0   
1954        Mike James        2018      2018        G    6-1   189.0   
1191     Patrick Ewing        2011      2011        F    6-8   235.0   
4405   Reggie Williams        2010      2017        F    6-6   205.0   
514        Roger Brown        1973      1980        C   6-11   225.0   
3778         Sam Smith        1979      1980        G    6-4   200.0   
4410      Sam Williams        1982      1985        F    6-8   210.0   
1626      Tim Hardaway        2014      2018        G    6-6   205.0   
1938      Tony Jackson        1981      1981        G    6-0   170.0   
2787     Tony Mitchell        2014      2014        F    6-8   235.0   
3522    Walker Russell        2012      2012        G    6-0   170.0   

              birth_date                                     college  
424        July 28, 1943                        Princeton University  
1069  September 26, 1940                          Colgate University  
2063     January 9, 1984                    University of Washington  
4431    January 15, 1951                    Wichita State Uni

There are quite a few duplicate names, and after further analysis, I haven't found a clean way to merge all tables with the duplicate names. Therefore, we will remove them altogether.

In [18]:
remove = playerInfoDf2.loc[playerInfoDf2['name'].duplicated()==True, :].index

playerInfoDf2.drop(index=remove, inplace=True)

We need to convert height into inches.

In [19]:
playerInfoDf2[['feet', 'inches']] = playerInfoDf2['height'].str.split('-', expand=True) # Split height on '-' 
                                                                                        # delimiter and put it in 
                                                                                        # feet and inches columns
playerInfoDf2.head()

name  year_start  year_end position height  weight  \
0       Alaa Abdelnaby        1991      1995      F-C   6-10   240.0   
1      Zaid Abdul-Aziz        1969      1978      C-F    6-9   235.0   
2  Kareem Abdul-Jabbar        1970      1989        C    7-2   225.0   
3   Mahmoud Abdul-Rauf        1991      2001        G    6-1   162.0   
4    Tariq Abdul-Wahad        1998      2003        F    6-6   223.0   

         birth_date                                college feet inches  
0     June 24, 1968                        Duke University    6     10  
1     April 7, 1946                  Iowa State University    6      9  
2    April 16, 1947  University of California, Los Angeles    7      2  
3     March 9, 1969             Louisiana State University    6      1  
4  November 3, 1974              San Jose State University    6      6

Now we need to make our new columns numeric:

In [20]:
playerInfoDf2['feet'] = pd.to_numeric(playerInfoDf2['feet'])
playerInfoDf2['inches'] = pd.to_numeric(playerInfoDf2['inches'])
playerInfoDf2.head()

name  year_start  year_end position height  weight  \
0       Alaa Abdelnaby        1991      1995      F-C   6-10   240.0   
1      Zaid Abdul-Aziz        1969      1978      C-F    6-9   235.0   
2  Kareem Abdul-Jabbar        1970      1989        C    7-2   225.0   
3   Mahmoud Abdul-Rauf        1991      2001        G    6-1   162.0   
4    Tariq Abdul-Wahad        1998      2003        F    6-6   223.0   

         birth_date                                college  feet  inches  
0     June 24, 1968                        Duke University   6.0    10.0  
1     April 7, 1946                  Iowa State University   6.0     9.0  
2    April 16, 1947  University of California, Los Angeles   7.0     2.0  
3     March 9, 1969             Louisiana State University   6.0     1.0  
4  November 3, 1974              San Jose State University   6.0     6.0

After attempting to convert the height to inches, I discovered that there was one NaN value for George Karl. We didn't have his position, height, or weight. Since he is a well-known player and coach, minimal research could be done to figure out this information. Therefore, I will add it here before converting height to inches.

In [21]:
# George Karl is only player with NaN for position, height, and
# and weight. Since he is a well-known coach, we can do research
# and find this info.

playerInfoDf2.loc[playerInfoDf2['name']=='George Karl', 'position'] = 'G'
playerInfoDf2.loc[playerInfoDf2['name']=='George Karl', 'height'] = '6-2'
playerInfoDf2.loc[playerInfoDf2['name']=='George Karl', 'weight'] = 185

Now, we can continue converting `height` to inches and remove our `feet` and `inches` columns.

In [22]:
playerInfoDf2['height'] = playerInfoDf2['feet']*12 + playerInfoDf2['inches']
playerInfoDf2.drop(columns=['feet', 'inches'], inplace=True)
playerInfoDf2.head()

name  year_start  year_end position  height  weight  \
0       Alaa Abdelnaby        1991      1995      F-C    82.0   240.0   
1      Zaid Abdul-Aziz        1969      1978      C-F    81.0   235.0   
2  Kareem Abdul-Jabbar        1970      1989        C    86.0   225.0   
3   Mahmoud Abdul-Rauf        1991      2001        G    73.0   162.0   
4    Tariq Abdul-Wahad        1998      2003        F    78.0   223.0   

         birth_date                                college  
0     June 24, 1968                        Duke University  
1     April 7, 1946                  Iowa State University  
2    April 16, 1947  University of California, Los Angeles  
3     March 9, 1969             Louisiana State University  
4  November 3, 1974              San Jose State University

Now, we will create a `born` column like the first data frame.

In [23]:
playerInfoDf2['born'] = pd.DatetimeIndex(playerInfoDf2['birth_date']).year
playerInfoDf2['born'] = [int(num) if math.isnan(num)==False else 'Unknown' for num in playerInfoDf2['born']]
playerInfoDf2['born'].head()

0    1968
1    1946
2    1947
3    1969
4    1974
Name: born, dtype: object

In [24]:
mergedPlayerDf = playerInfoDf1.merge(playerInfoDf2, how='left', left_on='name', right_on='name')
mergedPlayerDf.head()

name  height_x  weight_x                        college_x  \
0  Curly Armstrong      70.9     169.8               Indiana University   
1     Cliff Barker      74.0     183.0           University of Kentucky   
2    Leo Barnhorst      76.0     189.6         University of Notre Dame   
3       Ed Bartels      77.2     194.0  North Carolina State University   
4      Ralph Beard      70.1     174.2           University of Kentucky   

  born_x   birth_city birth_state  hall_of_fame  year_start  year_end  \
0   1918          NaN         NaN             0      1949.0    1951.0   
1   1921     Yorktown     Indiana             0      1950.0    1952.0   
2   1924          NaN         NaN             0      1950.0    1954.0   
3   1925          NaN         NaN             0      1950.0    1951.0   
4   1927  Hardinsburg    Kentucky             0      1950.0    1951.0   

  position  height_y  weight_y        birth_date  \
0      G-F      71.0     170.0  November 1, 1918   
1        G      74.0     185.0  January 15, 1921   
2      F-G      76.0     190.0      May 11, 1924   
3        F      77.0     195.0   October 8, 1925   
4        G      70.0     175.0  December 2, 1927   

                         college_y born_y  
0               Indiana University   1918  
1           University of Kentucky   1921  
2         University of Notre Dame   1924  
3  North Carolina State University   1925  
4           University of Kentucky   1927

In [25]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3922 entries, 0 to 3921
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height_x      3921 non-null   float64
 2   weight_x      3921 non-null   float64
 3   college_x     3573 non-null   object 
 4   born_x        3922 non-null   object 
 5   birth_city    3452 non-null   object 
 6   birth_state   3439 non-null   object 
 7   hall_of_fame  3922 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  height_y      3891 non-null   float64
 12  weight_y      3889 non-null   float64
 13  birth_date    3886 non-null   object 
 14  college_y     3618 non-null   object 
 15  born_y        3892 non-null   object 
dtypes: float64(6), int64(1), object(9)
memory usage: 520.9+ KB


Check for duplicated rows:

In [26]:
mergedPlayerDf.duplicated().sum()

0

Check for null values:

In [27]:
mergedPlayerDf.loc[mergedPlayerDf['name'].isna()==True, :]

name  height_x  weight_x college_x   born_x birth_city birth_state  \
223  NaN       NaN       NaN       NaN  Unknown        NaN         NaN   

     hall_of_fame  year_start  year_end position  height_y  weight_y  \
223             0         NaN       NaN      NaN       NaN       NaN   

    birth_date college_y born_y  
223        NaN       NaN    NaN

We'll drop this one row.

In [28]:
mergedPlayerDf.drop(index=223, inplace=True)

In [29]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height_x      3921 non-null   float64
 2   weight_x      3921 non-null   float64
 3   college_x     3573 non-null   object 
 4   born_x        3921 non-null   object 
 5   birth_city    3452 non-null   object 
 6   birth_state   3439 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  height_y      3891 non-null   float64
 12  weight_y      3889 non-null   float64
 13  birth_date    3886 non-null   object 
 14  college_y     3618 non-null   object 
 15  born_y        3892 non-null   object 
dtypes: float64(6), int64(1), object(9)
memory usage: 520.8+ KB


### Deal with `height` column<a name="first-second-subpoint"></a>

Let's take a look at the height_x and height_y columns.

In [30]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height_x      3921 non-null   float64
 2   weight_x      3921 non-null   float64
 3   college_x     3573 non-null   object 
 4   born_x        3921 non-null   object 
 5   birth_city    3452 non-null   object 
 6   birth_state   3439 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  height_y      3891 non-null   float64
 12  weight_y      3889 non-null   float64
 13  birth_date    3886 non-null   object 
 14  college_y     3618 non-null   object 
 15  born_y        3892 non-null   object 
dtypes: float64(6), int64(1), object(9)
memory usage: 520.8+ KB


Conveniently, `height_x` has one null value. Let's check it out.

In [31]:
mergedPlayerDf.loc[mergedPlayerDf['height_x'].isna()==True, :]

Empty DataFrame
Columns: [name, height_x, weight_x, college_x, born_x, birth_city, birth_state, hall_of_fame, year_start, year_end, position, height_y, weight_y, birth_date, college_y, born_y]
Index: []

We can do a quick Google search to find this out, and we will impute the proper value.

In [32]:
mergedPlayerDf.loc[mergedPlayerDf['height_x'].isna()==True, 'height_x'] = 74

In [33]:
# Sanity check
mergedPlayerDf.loc[mergedPlayerDf['height_x'].isna()==True, :]

Empty DataFrame
Columns: [name, height_x, weight_x, college_x, born_x, birth_city, birth_state, hall_of_fame, year_start, year_end, position, height_y, weight_y, birth_date, college_y, born_y]
Index: []

Since `height_x` has no null values, we will use that as the column for height and remove `height_y`.

In [34]:
mergedPlayerDf[['name', 'height_x', 'height_y']]

name  height_x  height_y
0       Curly Armstrong      70.9      71.0
1          Cliff Barker      74.0      74.0
2         Leo Barnhorst      76.0      76.0
3            Ed Bartels      77.2      77.0
4           Ralph Beard      70.1      70.0
...                 ...       ...       ...
3917      Troy Williams      78.0      79.0
3918       Kyle Wiltjer      81.9      82.0
3919  Stephen Zimmerman      83.9      84.0
3920        Paul Zipser      79.9      80.0
3921        Ivica Zubac      85.0      85.0

[3921 rows x 3 columns]

`height_x` has info in the first decimal point while `height_y` does not. While it probably wouldn't make a massive difference, we'll use `height_x` since it has slightly more detail. So, we'll delete `height_y` and rename `height_x` to just `height`.

In [35]:
mergedPlayerDf.drop(columns=['height_y'], inplace=True) # Dropping height_y

In [36]:
mergedPlayerDf.rename(columns={'height_x': 'height'}, inplace=True) # Rename height_x to height

In [37]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height        3921 non-null   float64
 2   weight_x      3921 non-null   float64
 3   college_x     3573 non-null   object 
 4   born_x        3921 non-null   object 
 5   birth_city    3452 non-null   object 
 6   birth_state   3439 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  weight_y      3889 non-null   float64
 12  birth_date    3886 non-null   object 
 13  college_y     3618 non-null   object 
 14  born_y        3892 non-null   object 
dtypes: float64(5), int64(1), object(9)
memory usage: 490.1+ KB


Great, now we'll move on to weight.

### Deal with `weight` column<a name="first-third-subpoint"></a>

`weight_x` has all non-null values while `weight_y` does have some. So we'll check which column is more informative.

In [38]:
mergedPlayerDf[['weight_x', 'weight_y']]

weight_x  weight_y
0        169.8     170.0
1        183.0     185.0
2        189.6     190.0
3        194.0     195.0
4        174.2     175.0
...        ...       ...
3917     213.9     218.0
3918     238.1     240.0
3919     238.1     240.0
3920     213.9     215.0
3921     264.6     265.0

[3921 rows x 2 columns]

Exactly like height, `weight_x` is more infomrative. Therefore, we will delete `weight_y` and rename `weight_x` to just `weight`.

In [39]:
mergedPlayerDf.drop(columns=['weight_y'], inplace=True) # Dropping weight_y

In [40]:
mergedPlayerDf.rename(columns={'weight_x': 'weight'}, inplace=True) # Rename weight_x to height

In [41]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height        3921 non-null   float64
 2   weight        3921 non-null   float64
 3   college_x     3573 non-null   object 
 4   born_x        3921 non-null   object 
 5   birth_city    3452 non-null   object 
 6   birth_state   3439 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  birth_date    3886 non-null   object 
 12  college_y     3618 non-null   object 
 13  born_y        3892 non-null   object 
dtypes: float64(4), int64(1), object(9)
memory usage: 459.5+ KB


### Deal with `college` column<a name="first-fourth-subpoint"></a>

Let's check for number of null values in each college column.

In [42]:
college_x_nulls = mergedPlayerDf['college_x'].isna().sum()
college_y_nulls = mergedPlayerDf['college_y'].isna().sum()
print(f'college_x number of null values: {college_x_nulls}')
print(f'college_y number of null values: {college_y_nulls}')

college_x number of null values: 348
college_y number of null values: 303


Both have a signficant number of null values. First, we'll see how many rows have null values for both columns.

In [43]:
college_x_is_null = mergedPlayerDf['college_x'].isna()
college_y_is_null = mergedPlayerDf['college_y'].isna()
both_null = college_x_is_null & college_y_is_null

mergedPlayerDf.loc[both_null, 'college_x'].isna().sum()

292

There are 293 rows that have both `college_x` and `college_y` as null values. We will edit `college_x` null values to hold the value 'Unknown'.

In [44]:
mergedPlayerDf.loc[both_null, 'college_x'] = 'Unknown'
mergedPlayerDf.tail() # Sanity check

name  height  weight                        college_x  \
3917      Troy Williams    78.0   213.9  South Carolina State University   
3918       Kyle Wiltjer    81.9   238.1               Gonzaga University   
3919  Stephen Zimmerman    83.9   238.1  University of Nevada, Las Vegas   
3920        Paul Zipser    79.9   213.9                          Unknown   
3921        Ivica Zubac    85.0   264.6                          Unknown   

     born_x      birth_city             birth_state  hall_of_fame  year_start  \
3917   1969        Columbia          South Carolina             0      2017.0   
3918   1992        Portland                  Oregon             0      2017.0   
3919   1996  Hendersonville               Tennessee             0      2017.0   
3920   1994      Heidelberg                 Germany             0      2017.0   
3921   1997          Mostar  Bosnia and Herzegovina             0      2017.0   

      year_end position         birth_date                        college_y  \
3917    2018.0        F  December 30, 1994               Indiana University   
3918    2017.0        F   October 20, 1992               Gonzaga University   
3919    2017.0        C  September 9, 1996  University of Nevada, Las Vegas   
3920    2018.0      G-F  February 18, 1994                              NaN   
3921    2018.0        C     March 18, 1997                              NaN   

     born_y  
3917   1994  
3918   1992  
3919   1996  
3920   1994  
3921   1997

Looks good. Let's check to see how many null values we have remaining in `college_x`.

In [45]:
mergedPlayerDf['college_x'].isna().sum()

56

There are still 55 null values in there. Let's take a look to see how many null values in `college_x` do have values in `college_y`.

In [46]:
college_x_is_null = mergedPlayerDf['college_x'].isna()
college_y_is__not_null = mergedPlayerDf['college_y'].isna()==False
x_null_y_not_null = college_x_is_null & college_y_is__not_null

mergedPlayerDf.loc[x_null_y_not_null, :].count()

name            56
height          56
weight          56
college_x        0
born_x          56
birth_city       0
birth_state      0
hall_of_fame    56
year_start      56
year_end        56
position        56
birth_date      56
college_y       56
born_y          56
dtype: int64

There are all 55 remaining values that need filled. Since that's the case, we will set all of these null values equal to `college_y`.

In [47]:
mergedPlayerDf.loc[college_x_is_null, 'college_x'] = mergedPlayerDf.loc[college_x_is_null, 'college_y']

In [48]:
mergedPlayerDf.info() # Sanity check

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height        3921 non-null   float64
 2   weight        3921 non-null   float64
 3   college_x     3921 non-null   object 
 4   born_x        3921 non-null   object 
 5   birth_city    3452 non-null   object 
 6   birth_state   3439 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  birth_date    3886 non-null   object 
 12  college_y     3618 non-null   object 
 13  born_y        3892 non-null   object 
dtypes: float64(4), int64(1), object(9)
memory usage: 459.5+ KB


`college_x` is ready. We can delete `college_y` and rename `college_x` to `college`.

In [49]:
mergedPlayerDf.drop(columns=['college_y'], inplace=True) # Dropping college_y

In [50]:
mergedPlayerDf.rename(columns={'college_x': 'college'}, inplace=True) # Rename college_x to college

In [51]:
mergedPlayerDf.info() # Sanity check

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height        3921 non-null   float64
 2   weight        3921 non-null   float64
 3   college       3921 non-null   object 
 4   born_x        3921 non-null   object 
 5   birth_city    3452 non-null   object 
 6   birth_state   3439 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  birth_date    3886 non-null   object 
 12  born_y        3892 non-null   object 
dtypes: float64(4), int64(1), object(8)
memory usage: 428.9+ KB


Now, on to the `born` columns.

### Deal with `born` columns<a name="first-fifth-subpoint"></a>

Since `born_x` has no null values, we will use that as our main column.

In [52]:
mergedPlayerDf.drop(columns='born_y', inplace=True)

We'll rename the column `year_born` and convert it into an integer.

In [53]:
mergedPlayerDf.rename(columns={'born_x': 'year_born'}, inplace=True)

In [54]:
mergedPlayerDf['year_born'] = mergedPlayerDf['year_born'].astype(int)

In [55]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height        3921 non-null   float64
 2   weight        3921 non-null   float64
 3   college       3921 non-null   object 
 4   year_born     3921 non-null   int64  
 5   birth_city    3452 non-null   object 
 6   birth_state   3439 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  birth_date    3886 non-null   object 
dtypes: float64(4), int64(2), object(6)
memory usage: 398.2+ KB


### Deal with `birth_city`  and `birth_state` column<a name="first-sixth-subpoint"></a>

We're missing some cities and some states, so let's see how many we're working with.

In [56]:
missing_cities = mergedPlayerDf['birth_city'].isna().sum()
missing_states = mergedPlayerDf['birth_state'].isna().sum()
print(f'There are {missing_cities} null values in the birth_city column.')
print(f'There are {missing_states} null values in the birth_city column.')

There are 469 null values in the birth_city column.
There are 482 null values in the birth_city column.


Let's see if there are any birth cities that exist but have the state as null:

In [57]:
state_is_null = mergedPlayerDf['birth_state'].isna()==True
city_is_not_null = mergedPlayerDf['birth_city'].isna()==False
combined = state_is_null & city_is_not_null

mergedPlayerDf.loc[combined, :]

name  height  weight  \
133           Leo Mogus    76.0   189.6   
270          Dave Minor    74.0   183.0   
985         Ken Charles    74.8   178.6   
1055          Don Smith    74.0   189.6   
2041          Gary Voce    81.1   238.1   
2168         Doug Smith    74.0   189.6   
2592       Kornel David    81.1   233.7   
2637  Vladimir Stepania    83.9   235.9   
2709    Dalibor Bagaric    85.0   253.6   
3024        Donta Smith    74.0   189.6   
3249        Cheikh Samb    85.0   244.8   
3839         Ben Bentil    81.1   233.7   
3882         Thon Maker    85.0   213.9   

                                    college  year_born           birth_city  \
133             Youngstown State University       1921                 Ohio   
270   University of California, Los Angeles       1922             Missouri   
985                      Fordham University       1951  Trinidad and Tobago   
1055                University of Minnesota       1920            Minnesota   
2041               University of Notre Dame       1965              Jamaica   
2168                University of Minnesota       1920            Minnesota   
2592                                Unknown       1971              Hungary   
2637                                Unknown       1976              Georgia   
2709                                Unknown       1980              Croatia   
3024                University of Minnesota       1920            Minnesota   
3249                                Unknown       1984              Senegal   
3839                     Providence College       1995                Ghana   
3882                                Unknown       1997          South Sudan   

     birth_state  hall_of_fame  year_start  year_end position  \
133          NaN             0      1947.0    1951.0      F-C   
270          NaN             0      1952.0    1953.0      G-F   
985          NaN             0      1974.0    1978.0        G   
1055         NaN             0      1949.0    1949.0      G-F   
2041         NaN             0      1990.0    1990.0        F   
2168         NaN             0      1992.0    1996.0        F   
2592         NaN             0      1999.0    2001.0        F   
2637         NaN             0      1999.0    2004.0        C   
2709         NaN             0      2001.0    2003.0        C   
3024         NaN             0      2005.0    2006.0      G-F   
3249         NaN             0      2008.0    2009.0        C   
3839         NaN             0      2017.0    2017.0        F   
3882         NaN             0      2017.0    2018.0      F-C   

              birth_date  
133       April 13, 1921  
270    February 23, 1922  
985        July 10, 1951  
1055       July 27, 1920  
2041   November 24, 1965  
2168  September 17, 1969  
2592    October 22, 1971  
2637         May 8, 1976  
2709    February 7, 1980  
3024   November 27, 1983  
3249    October 22, 1984  
3839      March 29, 1995  
3882   February 25, 1997

It looks like there's a mix of problems here. Some are states in the city column and some are other countries. I'll start with moving the states into their proper column and putting the city as 'Unknown'.

In [58]:
states = [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
    'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
    'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
    'New Jersey', 'New Mexico', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
    'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
    'Texas', 'Utah', 'Vermont', 'Virginia', 'West Virginia', 'Wisconsin', 'Wyoming']
# Excluding Washington and New York as they are actual cities

# For cities with state names, making the birth_state the state that's in the birth_city column
mergedPlayerDf.loc[mergedPlayerDf['birth_city'].isin(states), 'birth_state'] = mergedPlayerDf.loc[mergedPlayerDf['birth_state'].isin(states), 'birth_state']

# For cities with state names, making the city a NaN value
mergedPlayerDf.loc[mergedPlayerDf['birth_city'].isin(states), 'birth_city'] = 'Unknown'

In [59]:
mergedPlayerDf.loc[mergedPlayerDf['birth_city'].isin(states), :] # Sanity check to make sure states in the city column

Empty DataFrame
Columns: [name, height, weight, college, year_born, birth_city, birth_state, hall_of_fame, year_start, year_end, position, birth_date]
Index: []

In [60]:
mergedPlayerDf.loc[combined, :] # Checking for what's left of birth cities without a birth state

name  height  weight  \
133           Leo Mogus    76.0   189.6   
270          Dave Minor    74.0   183.0   
985         Ken Charles    74.8   178.6   
1055          Don Smith    74.0   189.6   
2041          Gary Voce    81.1   238.1   
2168         Doug Smith    74.0   189.6   
2592       Kornel David    81.1   233.7   
2637  Vladimir Stepania    83.9   235.9   
2709    Dalibor Bagaric    85.0   253.6   
3024        Donta Smith    74.0   189.6   
3249        Cheikh Samb    85.0   244.8   
3839         Ben Bentil    81.1   233.7   
3882         Thon Maker    85.0   213.9   

                                    college  year_born           birth_city  \
133             Youngstown State University       1921              Unknown   
270   University of California, Los Angeles       1922              Unknown   
985                      Fordham University       1951  Trinidad and Tobago   
1055                University of Minnesota       1920              Unknown   
2041               University of Notre Dame       1965              Jamaica   
2168                University of Minnesota       1920              Unknown   
2592                                Unknown       1971              Hungary   
2637                                Unknown       1976              Unknown   
2709                                Unknown       1980              Croatia   
3024                University of Minnesota       1920              Unknown   
3249                                Unknown       1984              Senegal   
3839                     Providence College       1995                Ghana   
3882                                Unknown       1997          South Sudan   

     birth_state  hall_of_fame  year_start  year_end position  \
133          NaN             0      1947.0    1951.0      F-C   
270          NaN             0      1952.0    1953.0      G-F   
985          NaN             0      1974.0    1978.0        G   
1055         NaN             0      1949.0    1949.0      G-F   
2041         NaN             0      1990.0    1990.0        F   
2168         NaN             0      1992.0    1996.0        F   
2592         NaN             0      1999.0    2001.0        F   
2637         NaN             0      1999.0    2004.0        C   
2709         NaN             0      2001.0    2003.0        C   
3024         NaN             0      2005.0    2006.0      G-F   
3249         NaN             0      2008.0    2009.0        C   
3839         NaN             0      2017.0    2017.0        F   
3882         NaN             0      2017.0    2018.0      F-C   

              birth_date  
133       April 13, 1921  
270    February 23, 1922  
985        July 10, 1951  
1055       July 27, 1920  
2041   November 24, 1965  
2168  September 17, 1969  
2592    October 22, 1971  
2637         May 8, 1976  
2709    February 7, 1980  
3024   November 27, 1983  
3249    October 22, 1984  
3839      March 29, 1995  
3882   February 25, 1997

It's impossible to see which cities are actually countries. But for those we can see, we will switch to the state column.

In [61]:
known_countries = ['Trinidad and Tobago', 'Jamaica', 'Hungary', 'Croatia', 'Senegal', 'Ghana', 'South Sudan']
# Creating list of known countries

mergedPlayerDf.loc[mergedPlayerDf['birth_city'].isin(known_countries), 'birth_city'].value_counts()
# Checking how many rows contain these countries in the birth_city column

Jamaica                5
Trinidad and Tobago    1
Hungary                1
Croatia                1
Senegal                1
Ghana                  1
South Sudan            1
Name: birth_city, dtype: int64

In [62]:
# Changing the birth_state to be the country in birth_city
mergedPlayerDf.loc[mergedPlayerDf['birth_city'].isin(known_countries), 'birth_state'] = mergedPlayerDf.loc[mergedPlayerDf['birth_city'].isin(known_countries), 'birth_city']

In [63]:
# Changing the birth_city to a NaN
mergedPlayerDf.loc[mergedPlayerDf['birth_city'].isin(known_countries), 'birth_city'] = 'Unknown'

In [64]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height        3921 non-null   float64
 2   weight        3921 non-null   float64
 3   college       3921 non-null   object 
 4   year_born     3921 non-null   int64  
 5   birth_city    3452 non-null   object 
 6   birth_state   3446 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  birth_date    3886 non-null   object 
dtypes: float64(4), int64(2), object(6)
memory usage: 398.2+ KB


Check for cities that are null but state that is not null.

In [65]:
city_is_null = mergedPlayerDf['birth_city'].isnull()==True
state_is_not_null = mergedPlayerDf['birth_state'].isnull()==False
combined = city_is_null & state_is_not_null

mergedPlayerDf.loc[combined, :]

Empty DataFrame
Columns: [name, height, weight, college, year_born, birth_city, birth_state, hall_of_fame, year_start, year_end, position, birth_date]
Index: []

This wasn't informative. Let's now check for rows that have null values for both birth_city and birth_state.

In [66]:
city_is_null = mergedPlayerDf['birth_city'].isnull()==True
state_is_null = mergedPlayerDf['birth_state'].isnull()==True
combined = city_is_null & state_is_null

mergedPlayerDf.loc[combined, :]

name  height  weight                          college  \
0           Curly Armstrong    70.9   169.8               Indiana University   
2             Leo Barnhorst    76.0   189.6         University of Notre Dame   
3                Ed Bartels    77.2   194.0  North Carolina State University   
5                Gene Berce    70.9   174.2             Marquette University   
13              Bob Brannum    77.2   213.9        Michigan State University   
...                     ...     ...     ...                              ...   
3819       D'Angelo Russell    74.0   189.6            Ohio State University   
3828          Alan Williams    78.0   198.5                 Drake University   
3863           A.J. Hammons    78.0   218.3                Purdue University   
3907            Edy Tavares    83.1   253.6                          Unknown   
3914  Taurean Waller-Prince    72.0   194.0                Baylor University   

      year_born birth_city birth_state  hall_of_fame  year_start  year_end  \
0          1918        NaN         NaN             0      1949.0    1951.0   
2          1924        NaN         NaN             0      1950.0    1954.0   
3          1925        NaN         NaN             0      1950.0    1951.0   
5          1926        NaN         NaN             0      1950.0    1950.0   
13         1925        NaN         NaN             0      1950.0    1955.0   
...         ...        ...         ...           ...         ...       ...   
3819       1994        NaN         NaN             0      2016.0    2018.0   
3828       1948        NaN         NaN             0      2016.0    2017.0   
3863       1993        NaN         NaN             0      2017.0    2017.0   
3907       1997        NaN         NaN             0      2016.0    2017.0   
3914       1994        NaN         NaN             0      2017.0    2018.0   

     position         birth_date  
0         G-F   November 1, 1918  
2         F-G       May 11, 1924  
3           F    October 8, 1925  
5         G-F  November 22, 1926  
13        F-C       May 28, 1925  
...       ...                ...  
3819        G  February 23, 1996  
3828      F-C   January 28, 1993  
3863        C    August 27, 1992  
3907        C     March 22, 1992  
3914        F     March 22, 1994  

[469 rows x 12 columns]

Let's make all of these nulls 'Unknown'.

In [67]:
mergedPlayerDf.loc[mergedPlayerDf['birth_city'].isnull()==True, 'birth_city'] = 'Unknown'
mergedPlayerDf.loc[mergedPlayerDf['birth_state'].isnull()==True, 'birth_state'] = 'Unknown'

In [68]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height        3921 non-null   float64
 2   weight        3921 non-null   float64
 3   college       3921 non-null   object 
 4   year_born     3921 non-null   int64  
 5   birth_city    3921 non-null   object 
 6   birth_state   3921 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  birth_date    3886 non-null   object 
dtypes: float64(4), int64(2), object(6)
memory usage: 398.2+ KB


All nulls are gone from `birth_city` and `birth_state`. Let's move on to `year_start`.

### Deal with `year_start` column<a name="first-seventh-subpoint"></a>

In [69]:
mergedPlayerDf['year_start'].isna().sum()

29

There are only 29 null values. Let's see what we find with those rows with null values in the `year_start` column.

In [70]:
mergedPlayerDf.loc[mergedPlayerDf['year_start'].isnull()==True, :]

name  height  weight                            college  \
93              Wah Wah    70.9   169.8                            Unknown   
115   Johnny Macknowski    72.0   178.6              Seton Hall University   
209           Butch Van    72.0   169.8                            Unknown   
213          Whitey Von    76.0   202.9                            Unknown   
451             Hot Rod    76.0   183.0                            Unknown   
532          George Bon    72.8   174.2                            Unknown   
665            Dick Van    81.9   233.7                            Unknown   
666             Tom Van    81.9   233.7                            Unknown   
816            Norm Van    77.2   189.6                            Unknown   
819               Jo Jo    74.8   178.6                            Unknown   
1085           World B.    81.1   213.9                            Unknown   
1217            Jan Van    72.8   174.2                            Unknown   
1324        Micheal Ray    78.0   187.4                            Unknown   
1340          Billy Ray    81.1   218.3                            Unknown   
1397          Joe Barry    76.0   194.0    Georgia Institute of Technology   
1699          Eddie Lee    74.8   194.0                            Unknown   
1902          Vinny Del    78.0   194.0                            Unknown   
2309           Nick Van    83.1   249.2                            Unknown   
2441       Logan Vander    79.9   213.9  University of Wisconsin-Green Bay   
2484     Horacio Llamas    83.1   284.4            Grand Canyon University   
2574          Keith Van    81.9   229.3                            Unknown   
2706        Metta World    74.8   178.6                            Unknown   
3018         Peter John    89.0   258.0                            Unknown   
3241        Juan Carlos    79.9   202.9                            Unknown   
3307           Luc Mbah    79.1   218.3                            Unknown   
3544           Nando De    81.1   213.9                            Unknown   
3727      James Michael    78.0   198.5                            Unknown   
3822     Walter Tavares    87.0   258.0                            Unknown   
3884  Sheldon McClellan    77.2   198.5                University of Miami   

      year_born  birth_city birth_state  hall_of_fame  year_start  year_end  \
93         1921     Unknown     Unknown             0         NaN       NaN   
115        1923     Unknown     Unknown             0         NaN       NaN   
209        1922     Unknown     Unknown             0         NaN       NaN   
213        1921     Unknown     Unknown             0         NaN       NaN   
451        1935     Unknown     Unknown             0         NaN       NaN   
532        1939     Unknown     Unknown             0         NaN       NaN   
665        1940     Unknown     Unknown             0         NaN       NaN   
666        1940     Unknown     Unknown             0         NaN       NaN   
816        1939     Unknown     Unknown             0         NaN       NaN   
819        1947     Unknown     Unknown             0         NaN       NaN   
1085       1952     Unknown     Unknown             0         NaN       NaN   
1217       1950     Unknown     Unknown             0         NaN       NaN   
1324       1955     Unknown     Unknown             0         NaN       NaN   
1340       1957     Unknown     Unknown             0         NaN       NaN   
1397       1969     Oakland  California             0         NaN       NaN   
1699       1962     Unknown     Unknown             0         NaN       NaN   
1902       1963     Unknown     Unknown             0         NaN       NaN   
2309       1970     Unknown     Unknown             0         NaN       NaN   
2441       1971     Valders   Wisconsin             0         NaN       NaN   
2484       1973  El Rosario      Mexico             0         NaN       NaN   
2574       1977    

As you can see, we know almost nothing about these players. However, we may get some of this info from our next dataframe we merge with. So for now, we will leave all of these.

There are no more null values in `year_start` that we need to work with at the moment.

### Deal with `year_end` column<a name="first-eighth-subpoint"></a>

In [71]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height        3921 non-null   float64
 2   weight        3921 non-null   float64
 3   college       3921 non-null   object 
 4   year_born     3921 non-null   int64  
 5   birth_city    3921 non-null   object 
 6   birth_state   3921 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  birth_date    3886 non-null   object 
dtypes: float64(4), int64(2), object(6)
memory usage: 398.2+ KB


Done with this. On to `position`.

### Deal with `position` column<a name="first-nineth-subpoint"></a>

In [72]:
mergedPlayerDf['position'].value_counts()

G      1334
F      1077
C       450
F-C     349
G-F     306
C-F     191
F-G     185
Name: position, dtype: int64

In one of the tables, it showed only 'G', 'F', or 'C' for position. In the other, it sometimes showed their primary and secondary positions. We will keep the variability as the game has changed slowly over time where more players could play more positions. Therefore, this could give us valuable information in our analysis.

In [73]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height        3921 non-null   float64
 2   weight        3921 non-null   float64
 3   college       3921 non-null   object 
 4   year_born     3921 non-null   int64  
 5   birth_city    3921 non-null   object 
 6   birth_state   3921 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  birth_date    3886 non-null   object 
dtypes: float64(4), int64(2), object(6)
memory usage: 398.2+ KB


No nulls. Finally, we'll work on `birth_date`.

### Deal with `birth_date` column<a name="first-tenth-subpoint"></a>

The date of birth doesn't have a ton of value. I wonder if the only thing that has value is the month. Therefore, we will create a new column that gives the month of birth. For the null values, we will impute the average for the value.

In [74]:
mergedPlayerDf.dtypes

name             object
height          float64
weight          float64
college          object
year_born         int64
birth_city       object
birth_state      object
hall_of_fame      int64
year_start      float64
year_end        float64
position         object
birth_date       object
dtype: object

In [75]:
mergedPlayerDf['month_born'] = pd.DatetimeIndex(mergedPlayerDf['birth_date']).month
mergedPlayerDf['day_born'] = pd.DatetimeIndex(mergedPlayerDf['birth_date']).day
mergedPlayerDf.drop(columns=['birth_date'], inplace=True)

In [76]:
mergedPlayerDf.head()

name  height  weight                          college  \
0  Curly Armstrong    70.9   169.8               Indiana University   
1     Cliff Barker    74.0   183.0           University of Kentucky   
2    Leo Barnhorst    76.0   189.6         University of Notre Dame   
3       Ed Bartels    77.2   194.0  North Carolina State University   
4      Ralph Beard    70.1   174.2           University of Kentucky   

   year_born   birth_city birth_state  hall_of_fame  year_start  year_end  \
0       1918      Unknown     Unknown             0      1949.0    1951.0   
1       1921     Yorktown     Indiana             0      1950.0    1952.0   
2       1924      Unknown     Unknown             0      1950.0    1954.0   
3       1925      Unknown     Unknown             0      1950.0    1951.0   
4       1927  Hardinsburg    Kentucky             0      1950.0    1951.0   

  position  month_born  day_born  
0      G-F        11.0       1.0  
1        G         1.0      15.0  
2      F-G         5.0      11.0  
3        F        10.0       8.0  
4        G        12.0       2.0

Now we'll handle null values.

In [77]:
mergedPlayerDf.loc[mergedPlayerDf['month_born'].isna()==True, :]

name  height  weight                               college  \
93              Wah Wah    70.9   169.8                               Unknown   
115   Johnny Macknowski    72.0   178.6                 Seton Hall University   
209           Butch Van    72.0   169.8                               Unknown   
213          Whitey Von    76.0   202.9                               Unknown   
309        Mike O'Neill    74.8   209.5              University of California   
345       Frank Reddout    77.2   194.0                   Syracuse University   
373         Ken McBride    74.8   189.6  University of Maryland Eastern Shore   
391          Don Bielke    79.1   238.1                 Valparaiso University   
412         Bob Schafer    74.8   194.0                  Villanova University   
451             Hot Rod    76.0   183.0                               Unknown   
532          George Bon    72.8   174.2                               Unknown   
665            Dick Van    81.9   233.7                               Unknown   
666             Tom Van    81.9   233.7                               Unknown   
816            Norm Van    77.2   189.6                               Unknown   
819               Jo Jo    74.8   178.6                               Unknown   
1069       Bobby Wilson    76.0   183.0        West Virginia State University   
1085           World B.    81.1   213.9                               Unknown   
1217            Jan Van    72.8   174.2                               Unknown   
1324        Micheal Ray    78.0   187.4                               Unknown   
1340          Billy Ray    81.1   218.3                               Unknown   
1397          Joe Barry    76.0   194.0       Georgia Institute of Technology   
1699          Eddie Lee    74.8   194.0                               Unknown   
1902          Vinny Del    78.0   194.0                               Unknown   
2309           Nick Van    83.1   249.2                               Unknown   
2441       Logan Vander    79.9   213.9     University of Wisconsin-Green Bay   
2484     Horacio Llamas    83.1   284.4               Grand Canyon University   
2574          Keith Van    81.9   229.3                               Unknown   
2706        Metta World    74.8   178.6                               Unknown   
3018         Peter John    89.0   258.0                               Unknown   
3241        Juan Carlos    79.9   202.9                               Unknown   
3307           Luc Mbah    79.1   218.3                               Unknown   
3544           Nando De    81.1   213.9                               Unknown   
3727      James Michael    78.0   198.5                               Unknown   
3822     Walter Tavares    87.0   258.0                               Unknown   
3884  Sheldon McClellan    77.2   198.5                   University of Miami   

      year_born  birth_city birth_state  hall_of_fame  year_start  year_end  \
93         1921     Unknown     Unknown             0         NaN       NaN   
115        1923     Unknown     Unknown             0         NaN       NaN   
209        1922     Unknown     Unknown             0         NaN       NaN   
213        1921     Unknown     Unknown             0         NaN       NaN   
309        1928     Unknown     Unknown             0      1953.0    1953.0   
345        1935     Unknown     Unknown             0      1954.0    1954.0   
373        1928     Unknown     Unknown             0      1955.0    1955.0   
391        1931     Unknown     Unknown             0      1956.0    1956.0   
412        1935     Unknown     Unknown             0      1956.0    1957.0   
451        1935     Unknown     Unknown             0         NaN       NaN   
532        1939     Unknown     Unknown             0         NaN       NaN   
665        1940     Unknown     Unknown             0         NaN       NaN   
666        1940     Unknown     Unknown             0         NaN       NaN

In [78]:
mergedPlayerDf.loc[mergedPlayerDf['month_born'].isna()==True, 'month_born'] = mergedPlayerDf['month_born'].mean()
mergedPlayerDf.loc[mergedPlayerDf['day_born'].isna()==True, 'day_born'] = mergedPlayerDf['day_born'].mean()

In [79]:
# Check for nulls
mergedPlayerDf.loc[mergedPlayerDf['month_born'].isna()==True, :]

Empty DataFrame
Columns: [name, height, weight, college, year_born, birth_city, birth_state, hall_of_fame, year_start, year_end, position, month_born, day_born]
Index: []

In [80]:
mergedPlayerDf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3921 entries, 0 to 3921
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          3921 non-null   object 
 1   height        3921 non-null   float64
 2   weight        3921 non-null   float64
 3   college       3921 non-null   object 
 4   year_born     3921 non-null   int64  
 5   birth_city    3921 non-null   object 
 6   birth_state   3921 non-null   object 
 7   hall_of_fame  3921 non-null   int64  
 8   year_start    3892 non-null   float64
 9   year_end      3892 non-null   float64
 10  position      3892 non-null   object 
 11  month_born    3921 non-null   float64
 12  day_born      3921 non-null   float64
dtypes: float64(6), int64(2), object(5)
memory usage: 428.9+ KB


We'll now make `month_born` and `day_born` to integers.

In [81]:
mergedPlayerDf['month_born'] = mergedPlayerDf['month_born'].astype(int)
mergedPlayerDf['day_born'] = mergedPlayerDf['day_born'].astype(int)

We are done cleaning our player data! We'll save it here and move on to adding our player statistics.

In [82]:
cleanPlayerDf = mergedPlayerDf
cleanPlayerDf.head()

name  height  weight                          college  \
0  Curly Armstrong    70.9   169.8               Indiana University   
1     Cliff Barker    74.0   183.0           University of Kentucky   
2    Leo Barnhorst    76.0   189.6         University of Notre Dame   
3       Ed Bartels    77.2   194.0  North Carolina State University   
4      Ralph Beard    70.1   174.2           University of Kentucky   

   year_born   birth_city birth_state  hall_of_fame  year_start  year_end  \
0       1918      Unknown     Unknown             0      1949.0    1951.0   
1       1921     Yorktown     Indiana             0      1950.0    1952.0   
2       1924      Unknown     Unknown             0      1950.0    1954.0   
3       1925      Unknown     Unknown             0      1950.0    1951.0   
4       1927  Hardinsburg    Kentucky             0      1950.0    1951.0   

  position  month_born  day_born  
0      G-F          11         1  
1        G           1        15  
2      F-G           5        11  
3        F          10         8  
4        G          12         2

In [83]:
cleanPlayerDf.to_csv('cleanPlayerDf.csv')

-----

## Player Statistics Data<a name="second-point"></a>

### Importing Data<a name="second-first-subpoint"></a>

The data we will import next are the stats for each player, each season. So we'll import that dataframe, clean it, and merge it with the cleanPlayerDf.

In [84]:
# Import season stats
season_stats_df = pd.read_csv('/Users/aidenbailey/Documents/BrainStation_Class/Capstone/Data/Seasons_Stats.csv', index_col=0)
season_stats_df.head()

Year           Player  Pos   Age   Tm     G  GS  MP  PER    TS%  ...  \
0  1950.0  Curly Armstrong  G-F  31.0  FTW  63.0 NaN NaN  NaN  0.368  ...   
1  1950.0     Cliff Barker   SG  29.0  INO  49.0 NaN NaN  NaN  0.435  ...   
2  1950.0    Leo Barnhorst   SF  25.0  CHS  67.0 NaN NaN  NaN  0.394  ...   
3  1950.0       Ed Bartels    F  24.0  TOT  15.0 NaN NaN  NaN  0.312  ...   
4  1950.0       Ed Bartels    F  24.0  DNN  13.0 NaN NaN  NaN  0.308  ...   

     FT%  ORB  DRB  TRB    AST  STL  BLK  TOV     PF    PTS  
0  0.705  NaN  NaN  NaN  176.0  NaN  NaN  NaN  217.0  458.0  
1  0.708  NaN  NaN  NaN  109.0  NaN  NaN  NaN   99.0  279.0  
2  0.698  NaN  NaN  NaN  140.0  NaN  NaN  NaN  192.0  438.0  
3  0.559  NaN  NaN  NaN   20.0  NaN  NaN  NaN   29.0   63.0  
4  0.548  NaN  NaN  NaN   20.0  NaN  NaN  NaN   27.0   59.0  

[5 rows x 52 columns]

In [85]:
season_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24691 entries, 0 to 24690
Data columns (total 52 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Year    24624 non-null  float64
 1   Player  24624 non-null  object 
 2   Pos     24624 non-null  object 
 3   Age     24616 non-null  float64
 4   Tm      24624 non-null  object 
 5   G       24624 non-null  float64
 6   GS      18233 non-null  float64
 7   MP      24138 non-null  float64
 8   PER     24101 non-null  float64
 9   TS%     24538 non-null  float64
 10  3PAr    18839 non-null  float64
 11  FTr     24525 non-null  float64
 12  ORB%    20792 non-null  float64
 13  DRB%    20792 non-null  float64
 14  TRB%    21571 non-null  float64
 15  AST%    22555 non-null  float64
 16  STL%    20792 non-null  float64
 17  BLK%    20792 non-null  float64
 18  TOV%    19582 non-null  float64
 19  USG%    19640 non-null  float64
 20  blanl   0 non-null      float64
 21  OWS     24585 non-null  float64
 22

### General Cleaning Data<a name="second-second-subpoint"></a>

There are 24,691 rows but the column with the most entries has 24,624 entries (which is multiple columns). So let's see if we can find anything about those other 67 rows.

In [86]:
# Check for rows where the player name is NaN since that would be a useless row
season_stats_df[season_stats_df['Player'].isna()]

Year Player  Pos  Age   Tm   G  GS  MP  PER  TS%  ...  FT%  ORB  DRB  \
312     NaN    NaN  NaN  NaN  NaN NaN NaN NaN  NaN  NaN  ...  NaN  NaN  NaN   
487     NaN    NaN  NaN  NaN  NaN NaN NaN NaN  NaN  NaN  ...  NaN  NaN  NaN   
618     NaN    NaN  NaN  NaN  NaN NaN NaN NaN  NaN  NaN  ...  NaN  NaN  NaN   
779     NaN    NaN  NaN  NaN  NaN NaN NaN NaN  NaN  NaN  ...  NaN  NaN  NaN   
911     NaN    NaN  NaN  NaN  NaN NaN NaN NaN  NaN  NaN  ...  NaN  NaN  NaN   
...     ...    ...  ...  ...  ...  ..  ..  ..  ...  ...  ...  ...  ...  ...   
21678   NaN    NaN  NaN  NaN  NaN NaN NaN NaN  NaN  NaN  ...  NaN  NaN  NaN   
22252   NaN    NaN  NaN  NaN  NaN NaN NaN NaN  NaN  NaN  ...  NaN  NaN  NaN   
22864   NaN    NaN  NaN  NaN  NaN NaN NaN NaN  NaN  NaN  ...  NaN  NaN  NaN   
23516   NaN    NaN  NaN  NaN  NaN NaN NaN NaN  NaN  NaN  ...  NaN  NaN  NaN   
24095   NaN    NaN  NaN  NaN  NaN NaN NaN NaN  NaN  NaN  ...  NaN  NaN  NaN   

       TRB  AST  STL  BLK  TOV  PF  PTS  
312    NaN  NaN  NaN  NaN  NaN NaN  NaN  
487    NaN  NaN  NaN  NaN  NaN NaN  NaN  
618    NaN  NaN  NaN  NaN  NaN NaN  NaN  
779    NaN  NaN  NaN  NaN  NaN NaN  NaN  
911    NaN  NaN  NaN  NaN  NaN NaN  NaN  
...    ...  ...  ...  ...  ...  ..  ...  
21678  NaN  NaN  NaN  NaN  NaN NaN  NaN  
22252  NaN  NaN  NaN  NaN  NaN NaN  NaN  
22864  NaN  NaN  NaN  NaN  NaN NaN  NaN  
23516  NaN  NaN  NaN  NaN  NaN NaN  NaN  
24095  NaN  NaN  NaN  NaN  NaN NaN  NaN  

[67 rows x 52 columns]

There are the 67 rows. All the values are NaN so we will remove all those rows.

In [87]:
indexDropList = list(season_stats_df[season_stats_df['Player'].isna()].index) # Create list of indeces where all rows
                                                                              # are null

for index in indexDropList: # Loop through each index and remove the row
    season_stats_df.drop([index], inplace=True) 
    
season_stats_df[season_stats_df['Player'].isna()] # Sanity check

Empty DataFrame
Columns: [Year, Player, Pos, Age, Tm, G, GS, MP, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, blanl, OWS, DWS, WS, WS/48, blank2, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS]
Index: []

[0 rows x 52 columns]

In [88]:
season_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24624 entries, 0 to 24690
Data columns (total 52 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Year    24624 non-null  float64
 1   Player  24624 non-null  object 
 2   Pos     24624 non-null  object 
 3   Age     24616 non-null  float64
 4   Tm      24624 non-null  object 
 5   G       24624 non-null  float64
 6   GS      18233 non-null  float64
 7   MP      24138 non-null  float64
 8   PER     24101 non-null  float64
 9   TS%     24538 non-null  float64
 10  3PAr    18839 non-null  float64
 11  FTr     24525 non-null  float64
 12  ORB%    20792 non-null  float64
 13  DRB%    20792 non-null  float64
 14  TRB%    21571 non-null  float64
 15  AST%    22555 non-null  float64
 16  STL%    20792 non-null  float64
 17  BLK%    20792 non-null  float64
 18  TOV%    19582 non-null  float64
 19  USG%    19640 non-null  float64
 20  blanl   0 non-null      float64
 21  OWS     24585 non-null  float64
 22

There are two columns with only null values, `blanl` and `blank2`, so we will drop them.

In [89]:
season_stats_df.drop(columns=['blanl', 'blank2'], inplace=True)

In [90]:
season_stats_df.info() # Sanity check that columns were dropped

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24624 entries, 0 to 24690
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Year    24624 non-null  float64
 1   Player  24624 non-null  object 
 2   Pos     24624 non-null  object 
 3   Age     24616 non-null  float64
 4   Tm      24624 non-null  object 
 5   G       24624 non-null  float64
 6   GS      18233 non-null  float64
 7   MP      24138 non-null  float64
 8   PER     24101 non-null  float64
 9   TS%     24538 non-null  float64
 10  3PAr    18839 non-null  float64
 11  FTr     24525 non-null  float64
 12  ORB%    20792 non-null  float64
 13  DRB%    20792 non-null  float64
 14  TRB%    21571 non-null  float64
 15  AST%    22555 non-null  float64
 16  STL%    20792 non-null  float64
 17  BLK%    20792 non-null  float64
 18  TOV%    19582 non-null  float64
 19  USG%    19640 non-null  float64
 20  OWS     24585 non-null  float64
 21  DWS     24585 non-null  float64
 22

### Deal with `Year` column<a name="second-third-subpoint"></a>

For the `Year` column, we will rename it `year` and change the data type to integer. Since there are no null values, we shouldn't have any more work to do.

In [91]:
season_stats_df.rename(columns={'Year': 'year'}, inplace=True) # Renaming
season_stats_df['year'] = season_stats_df['year'].astype(int) # Change data type

In [92]:
# Check to confirm dtype changed to integer
season_stats_df['year'].dtypes

dtype('int64')

### Deal with `Player` column<a name="second-fourth-subpoint"></a>

Since we have no null values here as well, we will simply look at the format of the names and also rename the column to `name` to match the other df for ease of importing purposes.

In [93]:
season_stats_df.rename(columns={'Player': 'name'}, inplace=True) # Renaming

Like one of the player info dfs, hall of famers had an astrisk next to their name. So we will check well-known hall of famer Michael Jordan to see if this is the same format.

In [94]:
season_stats_df.loc[season_stats_df['name']=='Michael Jordan*', :]

year             name Pos   Age   Tm     G    GS      MP   PER    TS%  \
7716   1985  Michael Jordan*  SG  21.0  CHI  82.0  82.0  3144.0  25.8  0.592   
8094   1986  Michael Jordan*  SG  22.0  CHI  18.0   7.0   451.0  27.5  0.533   
8469   1987  Michael Jordan*  SG  23.0  CHI  82.0  82.0  3281.0  29.8  0.562   
8869   1988  Michael Jordan*  SG  24.0  CHI  82.0  82.0  3311.0  31.7  0.603   
9297   1989  Michael Jordan*  SG  25.0  CHI  81.0  81.0  3255.0  31.1  0.614   
9747   1990  Michael Jordan*  SG  26.0  CHI  82.0  82.0  3197.0  31.2  0.606   
10212  1991  Michael Jordan*  SG  27.0  CHI  82.0  82.0  3034.0  31.6  0.605   
10666  1992  Michael Jordan*  SG  28.0  CHI  80.0  80.0  3102.0  27.7  0.579   
11106  1993  Michael Jordan*  SG  29.0  CHI  78.0  78.0  3067.0  29.7  0.564   
12048  1995  Michael Jordan*  SG  31.0  CHI  17.0  17.0   668.0  22.1  0.493   
12528  1996  Michael Jordan*  SG  32.0  CHI  82.0  82.0  3090.0  29.4  0.582   
13096  1997  Michael Jordan*  SG  33.0  CHI  82.0  82.0  3106.0  27.8  0.567   
13654  1998  Michael Jordan*  SG  34.0  CHI  82.0  82.0  3181.0  25.2  0.533   
15751  2002  Michael Jordan*  SF  38.0  WAS  60.0  53.0  2093.0  20.7  0.468   
16240  2003  Michael Jordan*  SF  39.0  WAS  82.0  67.0  3031.0  19.3  0.491   

       ...    FT%    ORB    DRB    TRB    AST    STL    BLK    TOV     PF  \
7716   ...  0.845  167.0  367.0  534.0  481.0  196.0   69.0  291.0  285.0   
8094   ...  0.840   23.0   41.0   64.0   53.0   37.0   21.0   45.0   46.0   
8469   ...  0.857  166.0  264.0  430.0  377.0  236.0  125.0  272.0  237.0   
8869   ...  0.841  139.0  310.0  449.0  485.0  259.0  131.0  252.0  270.0   
9297   ...  0.850  149.0  503.0  652.0  650.0  234.0   65.0  290.0  247.0   
9747   ...  0.848  143.0  422.0  565.0  519.0  227.0   54.0  247.0  241.0   
10212  ...  0.851  118.0  374.0  492.0  453.0  223.0   83.0  202.0  229.0   
10666  ...  0.832   91.0  420.0  511.0  489.0  182.0   75.0  200.0  201.0   
11106  ...  0.837  135.0  387.0  522.0  428.0  221.0   61.0  207.0  188.0   
12048  ...  0.801   25.0   92.0  117.0   90.0   30.0   13.0   35.0   47.0   
12528  ...  0.834  148.0  395.0  543.0  352.0  180.0   42.0  197.0  195.0   
13096  ...  0.833  113.0  369.0  482.0  352.0  140.0   44.0  166.0  156.0   
13654  ...  0.784  130.0  345.0  475.0  283.0  141.0   45.0  185.0  151.0   
15751  ...  0.790   50.0  289.0  339.0  310.0   85.0   26.0  162.0  119.0   
16240  ...  0.821   71.0  426.0  497.0  311.0  123.0   39.0  173.0  171.0   

          PTS  
7716   2313.0  
8094    408.0  
8469   3041.0  
8869   2868.0  
9297   2633.0  
9747   2753.0  
10212  2580.0  
10666  2404.0  
11106  2541.0  
12048   457.0  
12528  2491.0  
13096  2431.0  
13654  2357.0  
15751  1375.0  
16240  1640.0  

[15 rows x 50 columns]

Confirmed, hall of famers have an astrisk next to their name. So we will remove that astrisk and create a colunn indicating a player's hall of fame status.

In [95]:
hall_of_fame_names = list(set(season_stats_df.loc[season_stats_df['name'].str.endswith('*')==True, 'name'].values))
hall_of_fame_names

['Walt Frazier*',
 'Bob McAdoo*',
 'Ralph Sampson*',
 'Phil Jackson*',
 'Bob Davies*',
 'Yao Ming*',
 'Guy Rodgers*',
 'David Thompson*',
 'Dennis Rodman*',
 'Jerry Sloan*',
 'Don Barksdale*',
 'George Gervin*',
 'Adrian Dantley*',
 'Bob Houbregs*',
 'John Stockton*',
 'Dick McGuire*',
 'Dikembe Mutombo*',
 'Drazen Petrovic*',
 'Slater Martin*',
 'George Yardley*',
 'Bill Bradley*',
 'Paul Arizin*',
 'K.C. Jones*',
 'Maurice Stokes*',
 'Rick Barry*',
 'Connie Hawkins*',
 'Karl Malone*',
 'Jack Twyman*',
 'Dennis Johnson*',
 'Alex English*',
 "Shaquille O'Neal*",
 'George Mikan*',
 'Frank Ramsey*',
 'Bernard King*',
 'Earl Monroe*',
 'Michael Jordan*',
 'Cliff Hagan*',
 'Sam Jones*',
 'Bob Cousy*',
 'Clyde Lovellette*',
 'Julius Erving*',
 'Jim Pollard*',
 'Billy Cunningham*',
 'Al Cervi*',
 'Alfred McGuire*',
 'Scottie Pippen*',
 'Mel Daniels*',
 'Jamaal Wilkes*',
 'Louie Dampier*',
 'Richie Guerin*',
 'Dominique Wilkins*',
 'Alonzo Mourning*',
 'Nat Clifton*',
 'Wayne Embry*',
 'Baile

In [96]:
season_stats_df['hall_of_fame'] = None

for name in season_stats_df['name']:
    if name in hall_of_fame_names: # If they are in the hall of fame...
        season_stats_df.loc[season_stats_df['name']==name, 'hall_of_fame'] = 1 # Indicate they are here
        season_stats_df.loc[season_stats_df['name']==name, 'name'] = name[:-1] # Remove the astrisk here

season_stats_df['hall_of_fame'].fillna(0, inplace=True)

In [97]:
# Sanity check to make sure there are no more names that end with an astrisk
season_stats_df.loc[season_stats_df['name'].str.endswith('*')==True, :]

Empty DataFrame
Columns: [year, name, Pos, Age, Tm, G, GS, MP, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, OWS, DWS, WS, WS/48, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, hall_of_fame]
Index: []

[0 rows x 51 columns]

In [98]:
# Check for known hall of famer to make sure the hall of fame column is displaying correctly
season_stats_df.loc[season_stats_df['name']=='Wilt Chamberlain', ['name', 'hall_of_fame']]

name  hall_of_fame
1473  Wilt Chamberlain             1
1593  Wilt Chamberlain             1
1706  Wilt Chamberlain             1
1827  Wilt Chamberlain             1
1962  Wilt Chamberlain             1
2099  Wilt Chamberlain             1
2100  Wilt Chamberlain             1
2101  Wilt Chamberlain             1
2239  Wilt Chamberlain             1
2366  Wilt Chamberlain             1
2507  Wilt Chamberlain             1
2690  Wilt Chamberlain             1
2893  Wilt Chamberlain             1
3100  Wilt Chamberlain             1
3345  Wilt Chamberlain             1
3615  Wilt Chamberlain             1

Looks great!

### Merge<a name="second-fifth-subpoint"></a>

Now we'll merge the cleanPlayerInfo df with the season_stats_info df.

After a lot of work, there is no clean way I could find to merge the duplicate names from the cleanPlayerDf to this df, so I will remove the duplicate names.

In [99]:
dup_names = cleanPlayerDf.loc[cleanPlayerDf['name'].duplicated()==True, ['name']].values
dup_names_list = [name[0] for name in dup_names]
dup_names_list = list(set(dup_names_list))

In [100]:
the_df = season_stats_df.merge(cleanPlayerDf, how='left', on='name')
the_df.head()

year             name  Pos   Age   Tm     G  GS  MP  PER    TS%  ...  \
0  1950  Curly Armstrong  G-F  31.0  FTW  63.0 NaN NaN  NaN  0.368  ...   
1  1950     Cliff Barker   SG  29.0  INO  49.0 NaN NaN  NaN  0.435  ...   
2  1950    Leo Barnhorst   SF  25.0  CHS  67.0 NaN NaN  NaN  0.394  ...   
3  1950       Ed Bartels    F  24.0  TOT  15.0 NaN NaN  NaN  0.312  ...   
4  1950       Ed Bartels    F  24.0  DNN  13.0 NaN NaN  NaN  0.308  ...   

                           college  year_born  birth_city  birth_state  \
0               Indiana University       1918     Unknown      Unknown   
1           University of Kentucky       1921    Yorktown      Indiana   
2         University of Notre Dame       1924     Unknown      Unknown   
3  North Carolina State University       1925     Unknown      Unknown   
4  North Carolina State University       1925     Unknown      Unknown   

   hall_of_fame_y  year_start  year_end  position  month_born  day_born  
0               0      1949.0    1951.0       G-F          11         1  
1               0      1950.0    1952.0         G           1        15  
2               0      1950.0    1954.0       F-G           5        11  
3               0      1950.0    1951.0         F          10         8  
4               0      1950.0    1951.0         F          10         8  

[5 rows x 63 columns]

In [101]:
drop_indeces = the_df.loc[the_df['name'].isin(dup_names_list), :].index # Indeces of all duplicate names

the_df.drop(index=drop_indeces, inplace=True)

In [102]:
the_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24586 entries, 0 to 24661
Data columns (total 63 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   year            24586 non-null  int64  
 1   name            24586 non-null  object 
 2   Pos             24586 non-null  object 
 3   Age             24578 non-null  float64
 4   Tm              24586 non-null  object 
 5   G               24586 non-null  float64
 6   GS              18195 non-null  float64
 7   MP              24100 non-null  float64
 8   PER             24063 non-null  float64
 9   TS%             24500 non-null  float64
 10  3PAr            18801 non-null  float64
 11  FTr             24487 non-null  float64
 12  ORB%            20754 non-null  float64
 13  DRB%            20754 non-null  float64
 14  TRB%            21533 non-null  float64
 15  AST%            22517 non-null  float64
 16  STL%            20754 non-null  float64
 17  BLK%            20754 non-null 

In [103]:
the_df.loc[the_df['year_start'].isna()==True, :]

year               name  Pos   Age   Tm     G    GS      MP   PER  \
117    1950            Wah Wah   PF  23.0  INO  60.0   NaN     NaN   NaN   
149    1950  Johnny Macknowski  G-F  27.0  SYR  59.0   NaN     NaN   NaN   
292    1950          Butch Van  G-F  27.0  NYK  56.0   NaN     NaN   NaN   
298    1950         Whitey Von  G-F  27.0  TOT  59.0   NaN     NaN   NaN   
299    1950         Whitey Von  G-F  27.0  TRI  26.0   NaN     NaN   NaN   
...     ...                ...  ...   ...  ...   ...   ...     ...   ...   
24056  2016        Metta World   SF  36.0  LAL  35.0   5.0   590.0   8.3   
24409  2017           Luc Mbah   SF  30.0  LAC  80.0  76.0  1787.0  10.3   
24410  2017      James Michael   PF  24.0  GSW  52.0   2.0   457.0  13.0   
24412  2017  Sheldon McClellan   SG  24.0  WAS  30.0   3.0   287.0  10.1   
24650  2017        Metta World   SF  37.0  LAL  25.0   2.0   160.0   6.2   

         TS%  ...                college  year_born  birth_city  birth_state  \
117    0.449  ...                Unknown       1921     Unknown      Unknown   
149    0.405  ...  Seton Hall University       1923     Unknown      Unknown   
292    0.456  ...                Unknown       1922     Unknown      Unknown   
298    0.405  ...                Unknown       1921     Unknown      Unknown   
299    0.400  ...                Unknown       1921     Unknown      Unknown   
...      ...  ...                    ...        ...         ...          ...   
24056  0.435  ...                Unknown       1974     Unknown      Unknown   
24409  0.581  ...                Unknown       1984     Unknown      Unknown   
24410  0.543  ...                Unknown       1992     Unknown      Unknown   
24412  0.518  ...    University of Miami       1992     Houston        Texas   
24650  0.380  ...                Unknown       1974     Unknown      Unknown   

       hall_of_fame_y  year_start  year_end  position  month_born  day_born  
117                 0         NaN       NaN       NaN           6        15  
149                 0         NaN       NaN       NaN           6        15  
292                 0         NaN       NaN       NaN           6        15  
298                 0         NaN       NaN       NaN           6        15  
299                 0         NaN       NaN       NaN           6        15  
...               ...         ...       ...       ...         ...       ...  
24056               0         NaN       NaN       NaN           6        15  
24409               0         NaN       NaN       NaN           6        15  
24410               0         NaN       NaN       NaN           6        15  
24412               0         NaN       NaN       NaN           6        15  
24650               0         NaN       NaN       NaN           6        15  

[234 rows x 63 columns]

### The Problem with Stats Before 1974<a name="second-sixth-subpoint"></a>

Many stats in the NBA were not recorded until 1974. So the question is, should we remove the columns of stats not recorded until then, or should we remove all data before 1974?

In my opinion, the game was much different before the 70s, and most statistical patterns are not relevant for today. Therefore, I believe we should remove all data before 1974 so we can keep as many columns as possible.

In [104]:
remove_indeces = the_df.loc[the_df['year']<1974, :].index

the_df.drop(index=remove_indeces, inplace=True)

### Deal with `Pos` and `position` column<a name="second-seventh-subpoint"></a>

In [105]:
the_df['Pos'].value_counts()

PF       4293
SG       4115
C        4101
PG       4044
SF       3999
PG-SG      28
C-PF       27
SF-SG      27
SG-PG      26
PF-C       25
SG-SF      25
PF-SF      23
SF-PF      20
SG-PF       3
C-SF        2
PG-SF       1
Name: Pos, dtype: int64

In [106]:
the_df['Pos'].value_counts().sum()

20759

In [107]:
the_df.loc[the_df['Pos']!=the_df['position'], ['name', 'Pos', 'position']]

name Pos position
3827   Zaid Abdul-Aziz   C      C-F
3829         Don Adams  SF        F
3830      Rick Adelman  PG        G
3831      Lucius Allen  PG        G
3832    Tiny Archibald  PG        G
...                ...  ..      ...
24655       Nick Young  SG      G-F
24656   Thaddeus Young  PF        F
24657      Cody Zeller  PF      C-F
24658     Tyler Zeller   C      F-C
24660      Paul Zipser  SF      G-F

[18480 rows x 3 columns]

In [108]:
the_df.loc[the_df['name']=='Michael Jordan', ['name', 'Pos', 'position']]

name Pos position
7681   Michael Jordan  SG      G-F
8059   Michael Jordan  SG      G-F
8434   Michael Jordan  SG      G-F
8834   Michael Jordan  SG      G-F
9262   Michael Jordan  SG      G-F
9712   Michael Jordan  SG      G-F
10177  Michael Jordan  SG      G-F
10632  Michael Jordan  SG      G-F
11073  Michael Jordan  SG      G-F
12017  Michael Jordan  SG      G-F
12498  Michael Jordan  SG      G-F
13067  Michael Jordan  SG      G-F
13626  Michael Jordan  SG      G-F
15727  Michael Jordan  SF      G-F
16216  Michael Jordan  SF      G-F

As you can see, there are some rows where the `Pos` and `position` are not the same. Therefore, we will indicate that `Pos` is the player's primary position that season while `position` is there position(s) throughout their career.

In [109]:
the_df.rename(columns={'Pos': 'season_position'}, inplace=True) # Renaming 'Pos'
the_df.rename(columns={'position': 'career_position'}, inplace=True) # Renaming 'position'

In [110]:
the_df.info() # Sanity check for renaming

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20759 entries, 3827 to 24661
Data columns (total 63 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   year             20759 non-null  int64  
 1   name             20759 non-null  object 
 2   season_position  20759 non-null  object 
 3   Age              20759 non-null  float64
 4   Tm               20759 non-null  object 
 5   G                20759 non-null  float64
 6   GS               18195 non-null  float64
 7   MP               20759 non-null  float64
 8   PER              20754 non-null  float64
 9   TS%              20677 non-null  float64
 10  3PAr             18801 non-null  float64
 11  FTr              20665 non-null  float64
 12  ORB%             20754 non-null  float64
 13  DRB%             20754 non-null  float64
 14  TRB%             20754 non-null  float64
 15  AST%             20754 non-null  float64
 16  STL%             20754 non-null  float64
 17  BLK%     

Now let's manage the null values in `career_position`.

In [111]:
# Creating smaller df to find all rows with no career_position
no_career_position_df = the_df.loc[the_df['career_position'].isna()==True, ['name', 'season_position', 'career_position']]
no_career_position_df

name season_position career_position
4037            Dick Van              SG             NaN
4038             Tom Van              SF             NaN
4039            Norm Van              PG             NaN
4059               Jo Jo              PG             NaN
4304            Dick Van              SG             NaN
...                  ...             ...             ...
24056        Metta World              SF             NaN
24409           Luc Mbah              SF             NaN
24410      James Michael              PF             NaN
24412  Sheldon McClellan              SG             NaN
24650        Metta World              SF             NaN

[188 rows x 3 columns]

In [112]:
# Filling in all NaN values in career_position column with either the only position that shows up in the 
# season_position or a combo of the first two that show up

# List of names that have no career_position
name_list_no_career_position = list(set(the_df.loc[the_df['career_position'].isna()==True, 'name'].values))

# List of indeces of rows that have no career_position
index_list_no_career_position = list(set(the_df.loc[the_df['career_position'].isna()==True, :].index))

# Loop through names to find career_position
for name in name_list_no_career_position:
    temp_df = pd.DataFrame() # Create temporary DataFrame
    temp_df['name'] = None # Create 'name' column in temporary DataFrame
    temp_df['position'] = None # Create 'position' column in temporary DataFrame
    
    # Loop through each row in the no_career_position_df to add to the temp_df to create a df that only is only
    # the single name we're evaluating and all of the positions that player holds in his career
    for df_row in no_career_position_df.values:
        if name==df_row[0]:
            new_row = [name, df_row[1]] # Create new row with name and position that year
            temp_df.loc[len(temp_df)] = new_row # Add that new row to the temp_df
        else:
            pass
    
    # Create of list of all of the positions the player held
    temp_df_positions = list(set(temp_df['position']))
    
    # Loop through all of the positions and make the career_position equal to...
    if '-' in temp_df_positions[0]: 
        career_position = temp_df_positions[0] # The first position if that first position is a combo of two positions
    elif len(temp_df_positions)==1:
        career_position = temp_df_positions[0] # The first position if the number of positions a player held is 1
    elif len(temp_df_positions) > 1: # A hyphenated combo of the first two positions a player held if he held more
                                     # than one position
        if '-' in (temp_df_positions[0] + temp_df_positions[1]):
            career_position = temp_df_positions[1]
        else:
            career_position = str(temp_df_positions[0]) + '-' + str(temp_df_positions[1])
    
    the_df.loc[the_df['name']==name, 'career_position'] = career_position

In [113]:
the_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20759 entries, 3827 to 24661
Data columns (total 63 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   year             20759 non-null  int64  
 1   name             20759 non-null  object 
 2   season_position  20759 non-null  object 
 3   Age              20759 non-null  float64
 4   Tm               20759 non-null  object 
 5   G                20759 non-null  float64
 6   GS               18195 non-null  float64
 7   MP               20759 non-null  float64
 8   PER              20754 non-null  float64
 9   TS%              20677 non-null  float64
 10  3PAr             18801 non-null  float64
 11  FTr              20665 non-null  float64
 12  ORB%             20754 non-null  float64
 13  DRB%             20754 non-null  float64
 14  TRB%             20754 non-null  float64
 15  AST%             20754 non-null  float64
 16  STL%             20754 non-null  float64
 17  BLK%     

There are no more NaN values in `career_position` or `season_position`, so we're good to go and can move on to `Age`.

### Deal with `Age` column<a name="second-eighth-subpoint"></a>

In [114]:
the_df['Age'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20759 entries, 3827 to 24661
Series name: Age
Non-Null Count  Dtype  
--------------  -----  
20759 non-null  float64
dtypes: float64(1)
memory usage: 324.4 KB


Let's take a look at those rows with a null value for `Age`.

In [115]:
the_df.loc[the_df['Age'].isna()==True, :]

Empty DataFrame
Columns: [year, name, season_position, Age, Tm, G, GS, MP, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, OWS, DWS, WS, WS/48, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, hall_of_fame_x, height, weight, college, year_born, birth_city, birth_state, hall_of_fame_y, year_start, year_end, career_position, month_born, day_born]
Index: []

[0 rows x 63 columns]

We'll impute the age of a player based on the year they were born and they year of the season.

In [116]:
the_df['Age'].fillna(the_df['year'] - the_df['year_born'], inplace=True)

Now we'll rename `Age` to `age`.

In [117]:
the_df.rename(columns={'Age': 'age'}, inplace=True)

In [118]:
the_df['age'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20759 entries, 3827 to 24661
Series name: age
Non-Null Count  Dtype  
--------------  -----  
20759 non-null  float64
dtypes: float64(1)
memory usage: 324.4 KB


There are no more null values, so we can move on to `Tm`.

### Deal with `Tm` column<a name="second-nineth-subpoint"></a>

In [119]:
the_df['Tm'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20759 entries, 3827 to 24661
Series name: Tm
Non-Null Count  Dtype 
--------------  ----- 
20759 non-null  object
dtypes: object(1)
memory usage: 324.4+ KB


There are no null values, so we will just rename this column `team`.

In [120]:
the_df.rename(columns={'Tm': 'team'}, inplace=True)

In [121]:
the_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20759 entries, 3827 to 24661
Data columns (total 63 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   year             20759 non-null  int64  
 1   name             20759 non-null  object 
 2   season_position  20759 non-null  object 
 3   age              20759 non-null  float64
 4   team             20759 non-null  object 
 5   G                20759 non-null  float64
 6   GS               18195 non-null  float64
 7   MP               20759 non-null  float64
 8   PER              20754 non-null  float64
 9   TS%              20677 non-null  float64
 10  3PAr             18801 non-null  float64
 11  FTr              20665 non-null  float64
 12  ORB%             20754 non-null  float64
 13  DRB%             20754 non-null  float64
 14  TRB%             20754 non-null  float64
 15  AST%             20754 non-null  float64
 16  STL%             20754 non-null  float64
 17  BLK%     

On to `G`.

### Deal with `G` column<a name="second-tenth-subpoint"></a>

This column indicates number of games played. So we will rename it to be clearer.

In [122]:
the_df.rename(columns={'G': 'games_played'}, inplace=True)

In [123]:
the_df['games_played'] = the_df['games_played'].astype(int)

In [124]:
the_df['games_played'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20759 entries, 3827 to 24661
Series name: games_played
Non-Null Count  Dtype
--------------  -----
20759 non-null  int64
dtypes: int64(1)
memory usage: 324.4 KB


### Deal with `GS` column<a name="second-eleventh-subpoint"></a>

This column indicates number of games started. So we will rename it to be clearer.

In [125]:
the_df.rename(columns={'GS': 'games_started'}, inplace=True)

In [126]:
the_df['games_started'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20759 entries, 3827 to 24661
Series name: games_started
Non-Null Count  Dtype  
--------------  -----  
18195 non-null  float64
dtypes: float64(1)
memory usage: 324.4 KB


In [127]:
the_df.loc[the_df['games_started'].isna()==True, :].tail()

year             name season_position   age team  games_played  \
6412  1981  Bill Willoughby              SF  23.0  HOU            55   
6413  1981    Brian Winters              SG  28.0  MIL            69   
6414  1981     Mike Woodson              SG  22.0  NYK            81   
6415  1981      Sam Worthen              PG  23.0  CHI            64   
6416  1981     Larry Wright              PG  26.0  DET            45   

      games_started      MP   PER    TS%  ...                       college  \
6412            NaN  1145.0  10.8  0.554  ...                       Unknown   
6413            NaN  1771.0  12.5  0.528  ...  University of South Carolina   
6414            NaN   949.0  10.9  0.474  ...            Indiana University   
6415            NaN   945.0   8.9  0.538  ...          Marquette University   
6416            NaN   997.0  11.1  0.504  ...    Grambling State University   

      year_born    birth_city  birth_state  hall_of_fame_y  year_start  \
6412       1957     Englewood   New Jersey               0      1976.0   
6413       1952      Rockaway     New York               0      1975.0   
6414       1958  Indianapolis      Indiana               0      1981.0   
6415       1958      Brooklyn     New York               0      1981.0   
6416       1954        Monroe    Louisiana               0      1977.0   

      year_end  career_position  month_born  day_born  
6412    1984.0              F-C           5        20  
6413    1983.0              G-F           3         1  
6414    1991.0              G-F           3        24  
6415    1982.0                G           1        17  
6416    1982.0                G          11        23  

[5 rows x 63 columns]

We don't have the data from 1981 and before. So we must impute the number of games tarted. We will base this off of minutes played since we will assume that the more minutes a player plays, the more games they're likely to start.

In [128]:
avg_games_started_per_minutes_played = the_df.loc[the_df['games_started'].isna()==False, 'games_started'].sum() / the_df.loc[the_df['games_started'].isna()==False, 'MP'].sum()


the_df['games_started'].fillna(avg_games_started_per_minutes_played*the_df['MP'], inplace=True)

In [129]:
the_df.loc[the_df['games_started'].isna()==True, :]

Empty DataFrame
Columns: [year, name, season_position, age, team, games_played, games_started, MP, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, OWS, DWS, WS, WS/48, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, hall_of_fame_x, height, weight, college, year_born, birth_city, birth_state, hall_of_fame_y, year_start, year_end, career_position, month_born, day_born]
Index: []

[0 rows x 63 columns]

Let's make sure there are no values where `games_played` is greater than `games_started`.

In [130]:
the_df['test'] = the_df['games_played'] - the_df['games_started']

In [131]:
the_df.loc[the_df['test'] < 0, :]

Empty DataFrame
Columns: [year, name, season_position, age, team, games_played, games_started, MP, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, OWS, DWS, WS, WS/48, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, hall_of_fame_x, height, weight, college, year_born, birth_city, birth_state, hall_of_fame_y, year_start, year_end, career_position, month_born, day_born, test]
Index: []

[0 rows x 64 columns]

In [132]:
the_df.drop(columns=['test'], inplace=True)

So far so good. We'll keep going to address the remaining NaNs.

For the remaining 489 rows with NaNs for games_started, we'll impute the value based on points scored since we'll assume points scored is the closest predictor (for those remaining which was in the 50s) to minutes played was the number of points player could score.

In [133]:
avg_games_started_per_points_scored = the_df.loc[the_df['games_started'].isna()==False, 'games_started'].sum() / the_df.loc[the_df['games_started'].isna()==False, 'PTS'].sum()

the_df['games_started'].fillna(avg_games_started_per_points_scored*the_df['PTS'], inplace=True)

In [134]:
the_df.loc[the_df['games_started'].isna()==True, :]

Empty DataFrame
Columns: [year, name, season_position, age, team, games_played, games_started, MP, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, OWS, DWS, WS, WS/48, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, hall_of_fame_x, height, weight, college, year_born, birth_city, birth_state, hall_of_fame_y, year_start, year_end, career_position, month_born, day_born]
Index: []

[0 rows x 63 columns]

Let's make sure there are no values where `games_played` is greater than `games_started`.

In [135]:
the_df['test'] = the_df['games_played'] - the_df['games_started']

In [136]:
the_df.loc[the_df['test'] < 0, :]

Empty DataFrame
Columns: [year, name, season_position, age, team, games_played, games_started, MP, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, OWS, DWS, WS, WS/48, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, hall_of_fame_x, height, weight, college, year_born, birth_city, birth_state, hall_of_fame_y, year_start, year_end, career_position, month_born, day_born, test]
Index: []

[0 rows x 64 columns]

Since there are some, we will assume these players started all of their games.

In [137]:
the_df.loc[the_df['test'] < 0, 'games_started'] = the_df.loc[the_df['test'] < 0, 'games_played']

In [138]:
the_df['test'] = the_df['games_played'] - the_df['games_started']

the_df.loc[the_df['test'] < 0, :]

Empty DataFrame
Columns: [year, name, season_position, age, team, games_played, games_started, MP, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, OWS, DWS, WS, WS/48, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, hall_of_fame_x, height, weight, college, year_born, birth_city, birth_state, hall_of_fame_y, year_start, year_end, career_position, month_born, day_born, test]
Index: []

[0 rows x 64 columns]

In [139]:
the_df.drop(columns=['test'], inplace=True)

In [140]:
the_df['games_started'] = the_df['games_started'].astype(int)

In [141]:
the_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20759 entries, 3827 to 24661
Data columns (total 63 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   year             20759 non-null  int64  
 1   name             20759 non-null  object 
 2   season_position  20759 non-null  object 
 3   age              20759 non-null  float64
 4   team             20759 non-null  object 
 5   games_played     20759 non-null  int64  
 6   games_started    20759 non-null  int64  
 7   MP               20759 non-null  float64
 8   PER              20754 non-null  float64
 9   TS%              20677 non-null  float64
 10  3PAr             18801 non-null  float64
 11  FTr              20665 non-null  float64
 12  ORB%             20754 non-null  float64
 13  DRB%             20754 non-null  float64
 14  TRB%             20754 non-null  float64
 15  AST%             20754 non-null  float64
 16  STL%             20754 non-null  float64
 17  BLK%     

Looks great! Moving on.

### Deal with `MP` column<a name="second-twelfth-subpoint"></a>

This column represents minutes played so we will rename the column accordingly.

In [142]:
the_df.rename(columns={'MP': 'minutes_played'}, inplace=True)

In [143]:
the_df['minutes_played'].isna().sum()

0

In [144]:
the_df.loc[the_df['minutes_played'].isna()==True, :].head()

Empty DataFrame
Columns: [year, name, season_position, age, team, games_played, games_started, minutes_played, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, OWS, DWS, WS, WS/48, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, hall_of_fame_x, height, weight, college, year_born, birth_city, birth_state, hall_of_fame_y, year_start, year_end, career_position, month_born, day_born]
Index: []

[0 rows x 63 columns]

We will base minutes played based on games started since the number of games started is a good indicator of how much time a player will get on the court.

In [145]:
avg_minutes_played_per_games_started = the_df.loc[the_df['minutes_played'].isna()==False, 'minutes_played'].sum() / the_df.loc[the_df['minutes_played'].isna()==False, 'games_started'].sum()

the_df['minutes_played'].fillna(avg_minutes_played_per_games_started*the_df['games_started'], inplace=True)

In [146]:
the_df.loc[the_df['minutes_played'].isna()==True, :].head()

Empty DataFrame
Columns: [year, name, season_position, age, team, games_played, games_started, minutes_played, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, OWS, DWS, WS, WS/48, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, hall_of_fame_x, height, weight, college, year_born, birth_city, birth_state, hall_of_fame_y, year_start, year_end, career_position, month_born, day_born]
Index: []

[0 rows x 63 columns]

In [147]:
the_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20759 entries, 3827 to 24661
Data columns (total 63 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   year             20759 non-null  int64  
 1   name             20759 non-null  object 
 2   season_position  20759 non-null  object 
 3   age              20759 non-null  float64
 4   team             20759 non-null  object 
 5   games_played     20759 non-null  int64  
 6   games_started    20759 non-null  int64  
 7   minutes_played   20759 non-null  float64
 8   PER              20754 non-null  float64
 9   TS%              20677 non-null  float64
 10  3PAr             18801 non-null  float64
 11  FTr              20665 non-null  float64
 12  ORB%             20754 non-null  float64
 13  DRB%             20754 non-null  float64
 14  TRB%             20754 non-null  float64
 15  AST%             20754 non-null  float64
 16  STL%             20754 non-null  float64
 17  BLK%     

### Deal with `PER` column<a name="second-thirteenth-subpoint"></a>

This column represents the statistic player efficiency rating which attempts to wrap up all of a player's numbers into one statistic. For efficiency, we will leave the column name as `PER`.

We will use `minutes_played` to calculate `PER` for players with NaN values in the `PER` column. We will assume a player gets more playing time when their PER is higher.

In [148]:
the_df.loc[the_df['PER'].isna()==True, :]

year            name season_position   age team  games_played  \
17765  2006      Josh Davis              PF  25.0  HOU             1   
18083  2006     Alex Scales              SG  27.0  SAS             1   
19047  2008  Stephane Lasme              SF  25.0  GSW             1   
20017  2010   JamesOn Curry              PG  24.0  LAC             1   
21906  2013    Damion James              SF  25.0  BRK             2   

       games_started  minutes_played  PER  TS%  ...  \
17765              0             0.0  NaN  NaN  ...   
18083              0             0.0  NaN  NaN  ...   
19047              0             0.0  NaN  NaN  ...   
20017              0             0.0  NaN  NaN  ...   
21906              0             0.0  NaN  NaN  ...   

                                   college  year_born      birth_city  \
17765                 University of Dayton       1955         Detroit   
18083                 University of Oregon       1978          Racine   
19047  University of Massachusetts Amherst       1982     Port-Gentil   
20017            Oklahoma State University       1986  Pleasant Grove   
21906        University of Texas at Austin       1987           Hobbs   

          birth_state  hall_of_fame_y  year_start  year_end  career_position  \
17765        Michigan               0      2004.0    2012.0                F   
18083       Wisconsin               0      2006.0    2006.0                G   
19047           Gabon               0      2008.0    2008.0                F   
20017  North Carolina               0      2010.0    2010.0                G   
21906      New Mexico               0      2011.0    2014.0              G-F   

       month_born  day_born  
17765           8        10  
18083           7         3  
19047          12        17  
20017           1         7  
21906          10         7  

[5 rows x 63 columns]

In [149]:
the_df['PER'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20759 entries, 3827 to 24661
Series name: PER
Non-Null Count  Dtype  
--------------  -----  
20754 non-null  float64
dtypes: float64(1)
memory usage: 324.4 KB


In [150]:
avg_per_per_minute_played = the_df.loc[the_df['PER'].isna()==False, 'PER'].sum() / the_df.loc[the_df['PER'].isna()==False, 'minutes_played'].sum()

the_df['PER'].fillna(avg_minutes_played_per_games_started*the_df['minutes_played'], inplace=True)

In [151]:
the_df['PER'].isna().mean()

0.0

There are no more null values, so we can move on to the next column.

### Deal with `TS%` column<a name="second-fourteenth-subpoint"></a>

This column represents True Shooting Percentage which is a well-known metric attempting to measure a player's scoring ability.

We will check necessary columns to see if we can impute the proper value.

In [152]:
the_df.loc[the_df['TS%'].isna()==True, ['TS%', 'PTS', 'FTA', 'FGA']]

TS%  PTS  FTA  FGA
4000   NaN  0.0  0.0  0.0
4139   NaN  0.0  0.0  0.0
4820   NaN  0.0  0.0  0.0
5295   NaN  0.0  0.0  0.0
5375   NaN  0.0  0.0  0.0
...    ...  ...  ...  ...
23611  NaN  0.0  0.0  0.0
23631  NaN  0.0  0.0  0.0
23988  NaN  0.0  0.0  0.0
24126  NaN  0.0  0.0  0.0
24314  NaN  0.0  0.0  0.0

[82 rows x 4 columns]

Since we have all 0s, we can say the TS% is also 0.

In [153]:
the_df.loc[the_df['TS%'].isna()==True, ['TS%']] = 0

In [154]:
# Check if there are remaining null values

the_df.loc[the_df['TS%'].isna()==True, ['TS%', 'PTS', 'FTA', 'FGA']]

Empty DataFrame
Columns: [TS%, PTS, FTA, FGA]
Index: []

### Deal with `3PAr` column<a name="second-fifteenth-subpoint"></a>

This column captures the percentage of shots taken that were 3 point shots.

In [155]:
the_df.loc[the_df['3PAr'].isna()==True, ['year']].value_counts().index

MultiIndex([(1978,),
            (1977,),
            (1979,),
            (1975,),
            (1976,),
            (1974,),
            (2014,),
            (1992,),
            (2001,),
            (2013,),
            (1999,),
            (2009,),
            (2006,),
            (1996,),
            (2016,),
            (2011,),
            (2007,),
            (2004,),
            (2002,),
            (2010,),
            (1998,),
            (1990,),
            (1994,),
            (1997,),
            (2000,),
            (2015,),
            (1988,),
            (1989,),
            (2008,),
            (2005,),
            (2017,),
            (1991,),
            (2003,),
            (1987,),
            (1986,),
            (1984,),
            (1995,),
            (1980,)],
           names=['year'])

You'll see that many of the years with higher null counts are earlier. It is likely this is due to the fact that the 3-point shot wasn't introduced until 1976. Because of that, we will imput 0% for all NaN values in this column.

In [156]:
the_df.loc[the_df['3PAr'].isna()==True, '3PAr'] = 0

In [157]:
# Check for remaining null values
the_df['3PAr'].isna().sum()

0

In [158]:
the_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20759 entries, 3827 to 24661
Data columns (total 63 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   year             20759 non-null  int64  
 1   name             20759 non-null  object 
 2   season_position  20759 non-null  object 
 3   age              20759 non-null  float64
 4   team             20759 non-null  object 
 5   games_played     20759 non-null  int64  
 6   games_started    20759 non-null  int64  
 7   minutes_played   20759 non-null  float64
 8   PER              20759 non-null  float64
 9   TS%              20759 non-null  float64
 10  3PAr             20759 non-null  float64
 11  FTr              20665 non-null  float64
 12  ORB%             20754 non-null  float64
 13  DRB%             20754 non-null  float64
 14  TRB%             20754 non-null  float64
 15  AST%             20754 non-null  float64
 16  STL%             20754 non-null  float64
 17  BLK%     

### Deal with `FTr` column<a name="second-sixteenth-subpoint"></a>

This is the Free Throw rate: FTA / FGA.

In [159]:
the_df.loc[the_df['FTr'].isna()==True, ['FTr', 'FTA']]

FTr  FTA
4000   NaN  0.0
4139   NaN  0.0
4820   NaN  0.0
5295   NaN  0.0
5375   NaN  0.0
...    ...  ...
23611  NaN  0.0
23631  NaN  0.0
23988  NaN  0.0
24126  NaN  0.0
24314  NaN  0.0

[94 rows x 2 columns]

Since these are all due to no free throws being attempted, we will imput 0 for the `FTr`.

In [160]:
the_df.loc[the_df['FTr'].isna()==True, ['FTr']] = 0

### Deal with `ORB` and  `ORB%` column<a name="second-eighteenth-subpoint"></a>

ORB is the number of offensive rebounds, and ORB% is the percent of team offensive rebounds that player got in the game.

In [161]:
the_df['ORB'].isna().mean()

0.0

In [162]:
the_df['ORB%'].isna().mean()

0.00024085938629028373

We will impute `ORB%` based on `ORB`.

In [163]:
avg_orbpercent_per_orb = the_df.loc[the_df['ORB%'].isna()==False, 'ORB%'].sum() / the_df.loc[the_df['ORB%'].isna()==False, 'ORB'].sum()

the_df['ORB%'].fillna(avg_orbpercent_per_orb*the_df['ORB'], inplace=True)

### Deal with `DRB` and  `DRB%` column<a name="second-nineteenth-subpoint"></a>

DRB is the number of defensive rebounds, and DRB% is the percent of team defensive rebounds that player got in the game.

In [164]:
the_df['DRB'].isna().mean()

0.0

In [165]:
the_df['DRB%'].isna().mean()

0.00024085938629028373

We will impute `DRB%` based on `DRB`.

In [166]:
avg_drbpercent_per_drb = the_df.loc[the_df['DRB%'].isna()==False, 'DRB%'].sum() / the_df.loc[the_df['DRB%'].isna()==False, 'DRB'].sum()

the_df['DRB%'].fillna(avg_drbpercent_per_drb*the_df['DRB'], inplace=True)

In [167]:
the_df['DRB%'].isna().mean()

0.0

### Deal with `TRB%` column<a name="second-twentieth-subpoint"></a>

`TRB%` is the percentage of rebounds a player is attempted to have grabbed while he is on the court.

In [168]:
the_df['TRB%'].isna().mean()

0.00024085938629028373

In [169]:
avg_trbpercent_per_trb = the_df.loc[the_df['TRB%'].isna()==False, 'TRB%'].sum() / the_df.loc[the_df['TRB%'].isna()==False, 'TRB'].sum()

the_df['TRB%'].fillna(avg_trbpercent_per_trb*the_df['TRB'], inplace=True)

In [170]:
the_df['TRB%'].isna().mean() # Sanity check

0.0

### Deal with `AST%`, `STL%`, `BLK%`, `TOV%`, and `USG%` columns<a name="second-twenty-first-subpoint"></a>

In [171]:
the_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20759 entries, 3827 to 24661
Data columns (total 63 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   year             20759 non-null  int64  
 1   name             20759 non-null  object 
 2   season_position  20759 non-null  object 
 3   age              20759 non-null  float64
 4   team             20759 non-null  object 
 5   games_played     20759 non-null  int64  
 6   games_started    20759 non-null  int64  
 7   minutes_played   20759 non-null  float64
 8   PER              20759 non-null  float64
 9   TS%              20759 non-null  float64
 10  3PAr             20759 non-null  float64
 11  FTr              20759 non-null  float64
 12  ORB%             20759 non-null  float64
 13  DRB%             20759 non-null  float64
 14  TRB%             20759 non-null  float64
 15  AST%             20754 non-null  float64
 16  STL%             20754 non-null  float64
 17  BLK%     

This is exactly the same as `TRB%`:
- `AST%`: percent assists that came from a player while he was on the court
- `STL%`: percent steals that came from a player while he was on the court
- `BLK%`: percent blocks that came from a player while he was on the court
- `TOV%`: percent turnovers that came from a player while he was on the court
- `USG%`: percent plays that came from a player while he was on the court

In [172]:
print(the_df['AST%'].isna().mean())
print(the_df['STL%'].isna().mean())
print(the_df['BLK%'].isna().mean())
print(the_df['TOV%'].isna().mean())
print(the_df['USG%'].isna().mean())

0.00024085938629028373
0.00024085938629028373
0.00024085938629028373
0.058528830868538946
0.05573486198757165


We will impute the missing values by position average, except for `TOV%` and `USG%`. We are missing too many values for those two columns, so we will remove them.

In [173]:
the_df.drop(columns=['TOV%', 'USG%'], inplace=True)

In [174]:
the_df.reset_index(inplace=True)

In [175]:
# AST%
ast_by_position_df = pd.DataFrame(the_df.groupby('career_position')['AST%'].mean())

position_ast_dict = dict(zip(list(ast_by_position_df.index), list(ast_by_position_df['AST%'])))

indeces = the_df.loc[the_df['AST%'].isna()==True, :].index

for index in indeces:
    for position in position_ast_dict:
        if the_df.iloc[index, the_df.columns.get_loc('career_position')]==position:
            the_df.iloc[index, the_df.columns.get_loc('AST%')] = position_ast_dict[position]

In [176]:
# STL%
stl_by_position_df = pd.DataFrame(the_df.groupby('career_position')['STL%'].mean())

position_stl_dict = dict(zip(list(stl_by_position_df.index), list(stl_by_position_df['STL%'])))

indeces = the_df.loc[the_df['STL%'].isna()==True, :].index

for index in indeces:
    for position in position_stl_dict:
        if the_df.iloc[index, the_df.columns.get_loc('career_position')]==position:
            the_df.iloc[index, the_df.columns.get_loc('STL%')] = position_stl_dict[position]

In [177]:
# BLK%
blk_by_position_df = pd.DataFrame(the_df.groupby('career_position')['BLK%'].mean())

position_blk_dict = dict(zip(list(blk_by_position_df.index), list(blk_by_position_df['BLK%'])))

indeces = the_df.loc[the_df['BLK%'].isna()==True, :].index

for index in indeces:
    for position in position_blk_dict:
        if the_df.iloc[index, the_df.columns.get_loc('career_position')]==position:
            the_df.iloc[index, the_df.columns.get_loc('BLK%')] = position_blk_dict[position]

In [178]:
# Sanity check for remaining null values

print(the_df['AST%'].isna().mean())
print(the_df['STL%'].isna().mean())
print(the_df['BLK%'].isna().mean())

0.0
0.0
0.0


### Deal with `OWS` column<a name="second-twenty-second-subpoint"></a>

OWS stands for Offensive Win Shares which is a metric that estimates the number of wins a player produces from their team due to their offensive ability.

In [179]:
the_df['OWS'].isna().mean()

0.0

### Deal with `DWS` column<a name="one-more"></a>

DWS stands for Defensive Win Shares which is a metric that estimates the number of wins a player produces from their team due to their defensive ability.

In [180]:
the_df['DWS'].isna().mean()

0.0

### Deal with `WS` and `WS/48` column<a name="second-twenty-third-subpoint"></a>

`WS` is win share which measure the share of wins attributable to a player due to his performance.

In [181]:
print(the_df['WS'].isna().mean())
print(the_df['WS/48'].isna().mean())

0.0
0.00024085938629028373


We will impute based on `PER`.

In [182]:
# WS/48
avg_ws48_per_PER = the_df.loc[the_df['WS/48'].isna()==False, 'WS/48'].sum() / the_df.loc[the_df['WS/48'].isna()==False, 'PER'].sum()

the_df['WS/48'].fillna(avg_ws48_per_PER * the_df['PER'], inplace=True)

In [183]:
# Sanity check for remaining null values
the_df['WS/48'].isna().mean()

0.0

### Deal with `FG%` column<a name="second-twenty-sixth-subpoint"></a>

`FG%` is the field goal percentage which is the percentage of shots made by a player. Since we have all of the field goals attempted (`FGA`) and field goals made (`FG`), we can calculate the `FG%`.

In [184]:
the_df['FG%'].isna().mean()

0.004528156462257334

In [185]:
the_df.loc[the_df['FG%'].isna()==True, ['FG', 'FGA', 'FG%']]

FG  FGA  FG%
173    0.0  0.0  NaN
312    0.0  0.0  NaN
993    0.0  0.0  NaN
1468   0.0  0.0  NaN
1548   0.0  0.0  NaN
...    ...  ...  ...
19710  0.0  0.0  NaN
19730  0.0  0.0  NaN
20087  0.0  0.0  NaN
20225  0.0  0.0  NaN
20413  0.0  0.0  NaN

[94 rows x 3 columns]

We can see these NaNs exist because these players took 0 shots during the year. So we will imput 0 for the FG%.

In [186]:
the_df['FG%'].fillna(0, inplace=True)

In [187]:
the_df['FG%'].isna().mean()

0.0

### Deal with `3P`, `3PA`, and `3P%` columns<a name="second-twenty-seventh-subpoint"></a>

In [188]:
the_df.loc[the_df['3P%'].isna()==True, ['year', '3P', '3PA', '3P%']].groupby('year').count()
# Counting the rows where 0 3P were made and recorded

3P  3PA  3P%
year               
1974    0    0    0
1975    0    0    0
1976    0    0    0
1977    0    0    0
1978    0    0    0
1979    0    0    0
1980   84   84    0
1981   89   89    0
1982   81   81    0
1983   77   77    0
1984   84   84    0
1985   81   81    0
1986   82   82    0
1987   75   75    0
1988   85   85    0
1989   87   87    0
1990   84   84    0
1991   74   74    0
1992   85   85    0
1993   84   84    0
1994  105  105    0
1995   65   65    0
1996  100  100    0
1997  113  113    0
1998  100  100    0
1999  123  123    0
2000  101  101    0
2001  105  105    0
2002   95   95    0
2003   97   97    0
2004  130  130    0
2005  108  108    0
2006  121  121    0
2007  101  101    0
2008  116  116    0
2009  102  102    0
2010   93   93    0
2011  111  111    0
2012   99   99    0
2013   95   95    0
2014   96   96    0
2015   81   81    0
2016   56   56    0
2017   46   46    0

Again, the 3-point shot wasn't introduced until 1976. As you can see, most of the rows where there is not a 3-pointer recorded, it is before 1976. Therefore, we can imput 0 for `3P`, `3PA`, and `3P%`. For those that were recorded, we can just see that these players didn't make a 3-pointer in the given year. Once again, telling us we can impute a 0 for `3p%`.

In [189]:
the_df['3P'].fillna(0, inplace=True)
the_df['3PA'].fillna(0, inplace=True)
the_df['3P%'].fillna(0, inplace=True)

In [190]:
# Check for remaining nulls
print(the_df['3P'].isna().mean())
print(the_df['3PA'].isna().mean())
print(the_df['3P%'].isna().mean())

0.0
0.0
0.0


### Deal with `2P%` column<a name="second-twenty-eighth-subpoint"></a>

This column is the percentage of two-pointers made.

In [191]:
the_df.loc[the_df['2P%'].isna()==True, ['year', '2P', '2PA', '2P%']]

year   2P  2PA  2P%
173    1974  0.0  0.0  NaN
312    1975  0.0  0.0  NaN
993    1977  0.0  0.0  NaN
1468   1978  0.0  0.0  NaN
1548   1979  0.0  0.0  NaN
...     ...  ...  ...  ...
20225  2017  0.0  0.0  NaN
20413  2017  0.0  0.0  NaN
20418  2017  0.0  0.0  NaN
20516  2017  0.0  0.0  NaN
20691  2017  0.0  0.0  NaN

[123 rows x 4 columns]

Similar to `3P%`, the NaN values are due to the fact that a player took 0 2-point shots. Therefore, we will impute 0 as the `2P%`.

In [192]:
the_df['2P%'].fillna(0, inplace=True)

In [193]:
# Sanity check
the_df['2P%'].isna().mean()

0.0

### Deal with `eFG%` column<a name="second-twenty-ninth-subpoint"></a>

This column is Effective Field Goal Percentage which adjusts for the fact that a 3-pointer is worth more than a 2-pointer.

In [194]:
the_df['eFG%'].isna().mean()

0.004528156462257334

In [195]:
the_df.loc[the_df['eFG%'].isna()==True, ['eFG%', 'FGA']]

eFG%  FGA
173     NaN  0.0
312     NaN  0.0
993     NaN  0.0
1468    NaN  0.0
1548    NaN  0.0
...     ...  ...
19710   NaN  0.0
19730   NaN  0.0
20087   NaN  0.0
20225   NaN  0.0
20413   NaN  0.0

[94 rows x 2 columns]

Since `FGA` is the denominator of the calculation that gives us `eFG%`, it will give us a NaN if we try to compute it. Therefore, we will impute 0 for the NaNs.

In [196]:
the_df['eFG%'].fillna(0, inplace=True)

In [197]:
# Sanity check
the_df['eFG%'].isna().mean()

0.0

Let's see what we have left to clean up:

In [198]:
the_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20759 entries, 0 to 20758
Data columns (total 62 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   index            20759 non-null  int64  
 1   year             20759 non-null  int64  
 2   name             20759 non-null  object 
 3   season_position  20759 non-null  object 
 4   age              20759 non-null  float64
 5   team             20759 non-null  object 
 6   games_played     20759 non-null  int64  
 7   games_started    20759 non-null  int64  
 8   minutes_played   20759 non-null  float64
 9   PER              20759 non-null  float64
 10  TS%              20759 non-null  float64
 11  3PAr             20759 non-null  float64
 12  FTr              20759 non-null  float64
 13  ORB%             20759 non-null  float64
 14  DRB%             20759 non-null  float64
 15  TRB%             20759 non-null  float64
 16  AST%             20759 non-null  float64
 17  STL%        

### Deal with `FT%` column<a name="second-thirtieth-subpoint"></a>

This column is percentage of Free Throw shots made.

In [199]:
the_df['FT%'].isna().mean()

0.038152126788380945

In [200]:
the_df.loc[the_df['FT%'].isna()==True, ['FT%', 'FTA']]

FT%  FTA
13     NaN  0.0
72     NaN  0.0
138    NaN  0.0
141    NaN  0.0
173    NaN  0.0
...    ...  ...
20636  NaN  0.0
20688  NaN  0.0
20690  NaN  0.0
20691  NaN  0.0
20692  NaN  0.0

[792 rows x 2 columns]

Since there were 0 free throws attempted by these players in these years, we will impute 0 for the `FT%`.

In [201]:
the_df['FT%'].fillna(0, inplace=True)

### Deal with `TOV` column<a name="second-thirty-first-subpoint"></a>

turnovers were recorded starting after the 77-78 season. Therefore, we will seperate out those that have NaN values before and after that season to put in 0s for those after those years.

Let's start with those after those years.

In [202]:
# Turnovers after '77
from_77_on = the_df['year'] > 1977
blocks_are_nan = the_df['TOV'].isna()==True
both = from_77_on & blocks_are_nan

the_df.loc[both, 'TOV']

Series([], Name: TOV, dtype: float64)

Apparently there are no NaNs after 1977. So we just need to deal with those before that time period. Again, we are imputing based on positional average.

In [203]:
the_df['TOV'].isna().mean()

0.05549400260128137

In [204]:
# TOV
tov_by_position_df = pd.DataFrame(the_df.groupby('career_position')['TOV'].mean())
position_list = list(tov_by_position_df.index)
tov_list = list(tov_by_position_df['TOV'])

position_tov_df = the_df.loc[the_df['TOV'].isna()==True, ['career_position', 'TOV']]
tov_nan_index = list(position_tov_df.index)

for index1 in tov_nan_index:
    for index2 in range(len(position_list)):
        if the_df.iloc[index1][59]==position_list[index2]:
            the_df.iloc[index1, the_df.columns.get_loc('TOV')] = tov_list[index2]

In [205]:
the_df['TOV'].isna().mean()

0.0

### Deal with `hall_of_fame` columns<a name="second-thirty-second-subpoint"></a>

We have two `hall_of_fame` columns, so we need to make sure they show the same thing. Since each column is a 1 or 0 (1 indicating the player is currently in the hall of fame or 0 indicating he's not), we can create a temporary column subtracting the two values and make sure they equal 0.

In [206]:
the_df['test'] = the_df['hall_of_fame_x'] - the_df['hall_of_fame_y']
the_df.loc[the_df['test']!=0, ['name', 'hall_of_fame_x', 'hall_of_fame_y', 'test']]

Empty DataFrame
Columns: [name, hall_of_fame_x, hall_of_fame_y, test]
Index: []

Perfect, they all are good. So we will remove `hall_of_fame_y` and the `test` column to clean up.

In [207]:
the_df.drop(columns=['hall_of_fame_y', 'test'], inplace=True)

In [208]:
the_df.rename(columns={'hall_of_fame_x': 'hall_of_fame'}, inplace=True)

In [209]:
the_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20759 entries, 0 to 20758
Data columns (total 61 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   index            20759 non-null  int64  
 1   year             20759 non-null  int64  
 2   name             20759 non-null  object 
 3   season_position  20759 non-null  object 
 4   age              20759 non-null  float64
 5   team             20759 non-null  object 
 6   games_played     20759 non-null  int64  
 7   games_started    20759 non-null  int64  
 8   minutes_played   20759 non-null  float64
 9   PER              20759 non-null  float64
 10  TS%              20759 non-null  float64
 11  3PAr             20759 non-null  float64
 12  FTr              20759 non-null  float64
 13  ORB%             20759 non-null  float64
 14  DRB%             20759 non-null  float64
 15  TRB%             20759 non-null  float64
 16  AST%             20759 non-null  float64
 17  STL%        

Let's make sure this hall of fame list is up to date based on those who have been inducted into the hall of fame since 2017.

In [210]:
names = ['Tracy McGrady', 'George McGinnis', 'Ray Allen', 'Maurice Cheeks', 'Grant Hill', 'Jason Kidd', 'Steve Nash',
        'Charlie Scott', 'Carl Braun', 'Chuck Cooper', 'Vlade Divac', 'Bobby Jones', 'Sidney Moncrief', 'Jack Sikma',
        'Paul Westphal', 'Kobe Bryant', 'Tim Duncan', 'Kevin Garnett', 'Chris Bosh', 'Bob Dandridge', 'Toni Kukoc',
        'Paul Pierce', 'Ben Wallace', 'Chris Webber', 'Manu Ginobili', 'Tim Hardaway', 'Lou Hudson']

In [211]:
len(names)

27

In [212]:
the_df.loc[the_df['name']=='Tim Hardaway', 'hall_of_fame']

5828     0
6301     0
6749     0
7191     0
8124     0
8598     0
8599     0
8600     0
9158     0
9714     0
10246    0
10755    0
11253    0
11783    0
11784    0
11785    0
12269    0
18575    0
19184    0
19791    0
20374    0
Name: hall_of_fame, dtype: int64

Our list, names, has all of the players that have been inducted into the hall of fame since 2017. Now, we will update the hall_of_fame column in our df.

In [213]:
for name in names:
    the_df.loc[the_df['name']==name, 'hall_of_fame'] = 1

In [214]:
# Testing with Tim Hardaway
the_df.loc[the_df['name']=='Tim Hardaway', 'hall_of_fame']

5828     1
6301     1
6749     1
7191     1
8124     1
8598     1
8599     1
8600     1
9158     1
9714     1
10246    1
10755    1
11253    1
11783    1
11784    1
11785    1
12269    1
18575    1
19184    1
19791    1
20374    1
Name: hall_of_fame, dtype: int64

Perfect, on to the last couple columns.

### Deal with `year_start` and `year_end` columns<a name="second-thirty-third-subpoint"></a>

In [215]:
missing_years_df = the_df.loc[the_df['year_start'].isna()==True, ['name', 'year']]

indeces_missing_years = the_df.loc[the_df['year_start'].isna()==True, :].index

names = list(set(missing_years_df['name'].values))
indeces_missing_years

Int64Index([  210,   211,   212,   232,   477,   478,   479,   480,   481,
              506,
            ...
            19306, 19307, 19934, 19935, 20092, 20155, 20508, 20509, 20511,
            20747],
           dtype='int64', length=188)

In [216]:
for name in names:
    temp_df = pd.DataFrame()
    temp_df['name'] = None
    temp_df['year'] = None
    
    for df_row in missing_years_df.values:
        if df_row[0]==name:
            new_row = [name, df_row[1]]
            temp_df.loc[len(temp_df)] = new_row
        else:
            pass

    start = temp_df['year'].min()
    end = temp_df['year'].max()
        
    the_df.loc[the_df['name']==name, 'year_start'] = start
    the_df.loc[the_df['name']==name, 'year_end'] = end

This part is good to go. 

In analysis, it was found that some players were marked as their last year in the NBA being less than the year in which they have recorded stats. Here are those rows:

In [217]:
test_df = the_df

test_df['test'] = test_df['year_end'] - test_df['year']
bad_test = test_df.loc[test_df['test']<0, :]
bad_test[['name', 'year', 'year_start', 'year_end', 'test']]

name  year  year_start  year_end  test
21        Bill Bradley  1974      1968.0    1968.0  -6.0
79         Matt Guokas  1974      1947.0    1947.0 -27.0
80         Matt Guokas  1974      1947.0    1947.0 -27.0
81         Matt Guokas  1974      1947.0    1947.0 -27.0
82         Matt Guokas  1974      1947.0    1947.0 -27.0
...                ...   ...         ...       ...   ...
20481        David Lee  2017      1968.0    1969.0 -48.0
20499       John Lucas  2017      1977.0    1990.0 -27.0
20552      Larry Nance  2017      1982.0    1994.0 -23.0
20626   Glenn Robinson  2017      1995.0    2005.0 -12.0
20739  Reggie Williams  2017      1988.0    1997.0 -20.0

[230 rows x 5 columns]

These are some duplicate names. We will remove these similar to how we did at the beginning in merging process.

In [218]:
bad_indeces = bad_test.index
the_df.drop(index=bad_indeces, inplace=True)
the_df.drop(columns='test', inplace=True)

In [219]:
the_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20529 entries, 0 to 20758
Data columns (total 61 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   index            20529 non-null  int64  
 1   year             20529 non-null  int64  
 2   name             20529 non-null  object 
 3   season_position  20529 non-null  object 
 4   age              20529 non-null  float64
 5   team             20529 non-null  object 
 6   games_played     20529 non-null  int64  
 7   games_started    20529 non-null  int64  
 8   minutes_played   20529 non-null  float64
 9   PER              20529 non-null  float64
 10  TS%              20529 non-null  float64
 11  3PAr             20529 non-null  float64
 12  FTr              20529 non-null  float64
 13  ORB%             20529 non-null  float64
 14  DRB%             20529 non-null  float64
 15  TRB%             20529 non-null  float64
 16  AST%             20529 non-null  float64
 17  STL%        

### `birth_city` and `birth_state`

City isn't very informative as much as state. So we'll drop city and keep state to see if there's any significance at the state level.

In [220]:
the_df.drop(columns='birth_city', inplace=True)

In [221]:
the_df = pd.get_dummies(the_df, columns = ['birth_state'])
the_df.head()

index  year                 name season_position   age team  games_played  \
0   3827  1974      Zaid Abdul-Aziz               C  27.0  HOU            79   
1   3828  1974  Kareem Abdul-Jabbar               C  26.0  MIL            81   
2   3829  1974            Don Adams              SF  26.0  DET            74   
3   3830  1974         Rick Adelman              PG  27.0  CHI            55   
4   3831  1974         Lucius Allen              PG  26.0  MIL            72   

   games_started  minutes_played   PER  ...  \
0             50          2459.0  15.9  ...   
1             72          3548.0  24.4  ...   
2             46          2298.0  10.9  ...   
3             12           618.0  10.0  ...   
4             48          2388.0  18.8  ...   

   birth_state_United Republic of Tanzania  birth_state_Unknown  \
0                                        0                    0   
1                                        0                    0   
2                                        0                    0   
3                                        0                    0   
4                                        0                    0   

   birth_state_Uruguay  birth_state_Utah  birth_state_Venezuela  \
0                    0                 0                      0   
1                    0                 0                      0   
2                    0                 0                      0   
3                    0                 0                      0   
4                    0                 0                      0   

   birth_state_Virginia  birth_state_Washington  birth_state_West Virginia  \
0                     0                       0                          0   
1                     0                       0                          0   
2                     0                       0                          0   
3                     0                       0                          0   
4                     0                       0                          0   

   birth_state_Wisconsin  birth_state_Wyoming  
0                      0                    0  
1                      0                    0  
2                      0                    0  
3                      0                    0  
4                      0                    0  

[5 rows x 190 columns]

### `career_position` and `season_position`

We'll also convert `career_position` to binary columns and drop `season_position` so we can merge a player's rows to one so that we only have one player per row.

In [222]:
the_df = pd.get_dummies(the_df, columns = ['career_position'])
the_df.head()

index  year                 name season_position   age team  games_played  \
0   3827  1974      Zaid Abdul-Aziz               C  27.0  HOU            79   
1   3828  1974  Kareem Abdul-Jabbar               C  26.0  MIL            81   
2   3829  1974            Don Adams              SF  26.0  DET            74   
3   3830  1974         Rick Adelman              PG  27.0  CHI            55   
4   3831  1974         Lucius Allen              PG  26.0  MIL            72   

   games_started  minutes_played   PER  ...  career_position_G  \
0             50          2459.0  15.9  ...                  0   
1             72          3548.0  24.4  ...                  0   
2             46          2298.0  10.9  ...                  0   
3             12           618.0  10.0  ...                  1   
4             48          2388.0  18.8  ...                  1   

   career_position_G-F  career_position_PF  career_position_PF-SF  \
0                    0                   0                      0   
1                    0                   0                      0   
2                    0                   0                      0   
3                    0                   0                      0   
4                    0                   0                      0   

   career_position_PG  career_position_PG-SG  career_position_SF  \
0                   0                      0                   0   
1                   0                      0                   0   
2                   0                      0                   0   
3                   0                      0                   0   
4                   0                      0                   0   

   career_position_SF-PF  career_position_SF-SG  career_position_SG  
0                      0                      0                   0  
1                      0                      0                   0  
2                      0                      0                   0  
3                      0                      0                   0  
4                      0                      0                   0  

[5 rows x 205 columns]

In [223]:
the_df.drop(columns='season_position', inplace=True)

### `team` column

In [224]:
the_df = pd.get_dummies(the_df, columns = ['team'])
the_df.head()

index  year                 name   age  games_played  games_started  \
0   3827  1974      Zaid Abdul-Aziz  27.0            79             50   
1   3828  1974  Kareem Abdul-Jabbar  26.0            81             72   
2   3829  1974            Don Adams  26.0            74             46   
3   3830  1974         Rick Adelman  27.0            55             12   
4   3831  1974         Lucius Allen  26.0            72             48   

   minutes_played   PER    TS%  3PAr  ...  team_SAC  team_SAS  team_SDC  \
0          2459.0  15.9  0.516   0.0  ...         0         0         0   
1          3548.0  24.4  0.564   0.0  ...         0         0         0   
2          2298.0  10.9  0.457   0.0  ...         0         0         0   
3           618.0  10.0  0.447   0.0  ...         0         0         0   
4          2388.0  18.8  0.536   0.0  ...         0         0         0   

   team_SEA  team_TOR  team_TOT  team_UTA  team_VAN  team_WAS  team_WSB  
0         0         0         0         0         0         0         0  
1         0         0         0         0         0         0         0  
2         0         0         0         0         0         0         0  
3         0         0         0         0         0         0         0  
4         0         0         0         0         0         0         0  

[5 rows x 249 columns]

### `college` column

In [225]:
the_df = pd.get_dummies(the_df, columns = ['college'])
the_df.head()

index  year                 name   age  games_played  games_started  \
0   3827  1974      Zaid Abdul-Aziz  27.0            79             50   
1   3828  1974  Kareem Abdul-Jabbar  26.0            81             72   
2   3829  1974            Don Adams  26.0            74             46   
3   3830  1974         Rick Adelman  27.0            55             12   
4   3831  1974         Lucius Allen  26.0            72             48   

   minutes_played   PER    TS%  3PAr  ...  \
0          2459.0  15.9  0.516   0.0  ...   
1          3548.0  24.4  0.564   0.0  ...   
2          2298.0  10.9  0.457   0.0  ...   
3           618.0  10.0  0.447   0.0  ...   
4          2388.0  18.8  0.536   0.0  ...   

   college_Western Kentucky University  college_Western Michigan University  \
0                                    0                                    0   
1                                    0                                    0   
2                                    0                                    0   
3                                    0                                    0   
4                                    0                                    0   

   college_Wichita State University  college_William Paterson University  \
0                                 0                                    0   
1                                 0                                    0   
2                                 0                                    0   
3                                 0                                    0   
4                                 0                                    0   

   college_Wingate University  college_Winston-Salem State University  \
0                           0                                       0   
1                           0                                       0   
2                           0                                       0   
3                           0                                       0   
4                           0                                       0   

   college_Wright State University  college_Xavier University  \
0                                0                          0   
1                                0                          0   
2                                0                          0   
3                                0                          0   
4                                0                          0   

   college_Xavier University of Louisiana  college_Yale University  
0                                       0                        0  
1                                       0                        0  
2                                       0                        0  
3                                       0                        0  
4                                       0                        0  

[5 rows x 620 columns]

### Final Changes<a name="second-thirty-fourth-subpoint"></a>

We're going to make `year_start` and `year_end` integers. 

In [226]:
the_df['year_start'] = the_df['year_start'].astype(int)
the_df['year_end'] = the_df['year_end'].astype(int)

In [227]:
# Drop 'index' column
the_df.drop(columns='index', inplace=True)

----

Our df is clean and ready for EDA.

In [228]:
the_df.to_csv('clean_df.csv')

----

In [229]:
the_df.head()

year                 name   age  games_played  games_started  \
0  1974      Zaid Abdul-Aziz  27.0            79             50   
1  1974  Kareem Abdul-Jabbar  26.0            81             72   
2  1974            Don Adams  26.0            74             46   
3  1974         Rick Adelman  27.0            55             12   
4  1974         Lucius Allen  26.0            72             48   

   minutes_played   PER    TS%  3PAr    FTr  ...  \
0          2459.0  15.9  0.516   0.0  0.328  ...   
1          3548.0  24.4  0.564   0.0  0.239  ...   
2          2298.0  10.9  0.457   0.0  0.271  ...   
3           618.0  10.0  0.447   0.0  0.447  ...   
4          2388.0  18.8  0.536   0.0  0.258  ...   

   college_Western Kentucky University  college_Western Michigan University  \
0                                    0                                    0   
1                                    0                                    0   
2                                    0                                    0   
3                                    0                                    0   
4                                    0                                    0   

   college_Wichita State University  college_William Paterson University  \
0                                 0                                    0   
1                                 0                                    0   
2                                 0                                    0   
3                                 0                                    0   
4                                 0                                    0   

   college_Wingate University  college_Winston-Salem State University  \
0                           0                                       0   
1                           0                                       0   
2                           0                                       0   
3                           0                                       0   
4                           0                                       0   

   college_Wright State University  college_Xavier University  \
0                                0                          0   
1                                0                          0   
2                                0                          0   
3                                0                          0   
4                                0                          0   

   college_Xavier University of Louisiana  college_Yale University  
0                                       0                        0  
1                                       0                        0  
2                                       0                        0  
3                                       0                        0  
4                                       0                        0  

[5 rows x 619 columns]